#
# ----
101com.com
101order.com
123found.com
123freeavatars.com
127.0.0.1 101com.com
127.0.0.1 101order.com
127.0.0.1 123found.com
127.0.0.1 123freeavatars.com
127.0.0.1 180hits.de
127.0.0.1 180searchassistant.com
127.0.0.1 207.net
127.0.0.1 247media.com
127.0.0.1 24log.com
127.0.0.1 24log.de
127.0.0.1 24pm-affiliation.com
127.0.0.1 2mdn.net
127.0.0.1 2o7.net
127.0.0.1 360yield.com
127.0.0.1 4affiliate.net
127.0.0.1 4d5.net
127.0.0.1 50websads.com
127.0.0.1 518ad.com
127.0.0.1 51yes.com
127.0.0.1 600z.com
127.0.0.1 777partner.com
127.0.0.1 77tracking.com
127.0.0.1 7bpeople.com
127.0.0.1 7search.com
127.0.0.1 99count.com
127.0.0.1 a.0day.kiev.ua
127.0.0.1 a32.g.a.yimg.com
127.0.0.1 aaddzz.com
127.0.0.1 a-ads.com
127.0.0.1 a.aproductmsg.com
127.0.0.1 abacho.net
127.0.0.1 abandonedclover.com
127.0.0.1 abc-ads.com
127.0.0.1 abruptroad.com
127.0.0.1 absoluteclickscom.com
127.0.0.1 abz.com
127.0.0.1 accounts.pkr.com.invalid
127.0.0.1 a.collective-media.net
127.0.0.1 a.consumer.net
127.0.0.1 a-counter.kiev.ua
127.0.0.1 ac.rnm.ca
127.0.0.1 acsseo.com
127.0.0.1 actionsplash.com
127.0.0.1 actualdeals.com
127.0.0.1 actuallysheep.com
127.0.0.1 acuityads.com
127.0.0.1 acuty1adsrv.com
127.0.0.1 ad01.mediacorpsingapore.com
127.0.0.1 ad0.bigmir.net
127.0.0.1 ad.100.tbn.ru
127.0.0.1 ad1.emediate.dk
127.0.0.1 ad1.emule-project.org
127.0.0.1 ad1.kde.cz
127.0.0.1 ad1.pamedia.com.au
127.0.0.1 ad2flash.com
127.0.0.1 ad2games.com
127.0.0.1 ad2games.com.invalid
127.0.0.1 ad2.iinfo.cz
127.0.0.1 ad2.linxcz.cz
127.0.0.1 ad2.lupa.cz
127.0.0.1 ad2.xrea.com
127.0.0.1 ad3.iinfo.cz
127.0.0.1 ad3.pamedia.com.au
127.0.0.1 ad3.xrea.com
127.0.0.1 ad4game.com
127.0.0.1 ad.71i.de
127.0.0.1 ad.a8.net
127.0.0.1 ad.abcnews.com
127.0.0.1 ad.abctv.com
127.0.0.1 ad.aboutwebservices.com
127.0.0.1 ad.abum.com
127.0.0.1 adaction.de
127.0.0.1 ad.admitad.com
127.0.0.1 adadvisor.net
127.0.0.1 ad.afy11.net
127.0.0.1 ad.allstar.cz
127.0.0.1 ad.altervista.org
127.0.0.1 ad.amgdgt.com
127.0.0.1 ad.anuntis.com
127.0.0.1 adapt.tv
127.0.0.1 adap.tv
127.0.0.1 ad.auditude.com
127.0.0.1 ad-balancer.at
127.0.0.1 ad-balancer.net
127.0.0.1 adbanner.ro
127.0.0.1 adbard.net
127.0.0.1 ad.bizo.com
127.0.0.1 adblade.com
127.0.0.1 adblockanalytics.com
127.0.0.1 ad.bnmla.com
127.0.0.1 ad.bondage.com
127.0.0.1 adboost.de.vu
127.0.0.1 adboost.net
127.0.0.1 adbooth.net
127.0.0.1 adbot.com
127.0.0.1 adbrite.com
127.0.0.1 adbroker.de
127.0.0.1 adbunker.com
127.0.0.1 adbutler.com
127.0.0.1 adbutler.de
127.0.0.1 adbuyer3.lycos.com
127.0.0.1 adbuyer.com
127.0.0.1 ad.caradisiac.com
127.0.0.1 adcash.com
127.0.0.1 adcast.deviantart.com
127.0.0.1 adcell.de
127.0.0.1 ad-center.com
127.0.0.1 adcenter.mdf.se
127.0.0.1 adcenter.net
127.0.0.1 adcentriconline.com
127.0.0.1 ad.centrum.cz
127.0.0.1 adcept.net
127.0.0.1 ad.cgi.cz
127.0.0.1 ad.choiceradio.com
127.0.0.1 adclick.com
127.0.0.1 adclient1.tucows.com
127.0.0.1 adclient.uimserv.net
127.0.0.1 ad.clix.pt
127.0.0.1 adcomplete.com
127.0.0.1 adconion.com
127.0.0.1 adcontent.gamespy.com
127.0.0.1 ad.cooks.com
127.0.0.1 ad.crwdcntrl.net
127.0.0.1 adcycle.com
127.0.0.1 addfreestats.com
127.0.0.1 ad.digitallook.com
127.0.0.1 ad.directrev.com
127.0.0.1 addme.com
127.0.0.1 add.newmedia.cz
127.0.0.1 ad.doctissimo.fr
127.0.0.1 ad.domainfactory.de
127.0.0.1 adecn.com
127.0.0.1 ad.e-kolay.net
127.0.0.1 ademails.com
127.0.0.1 adengage.com
127.0.0.1 ad.eurosport.com
127.0.0.1 adexchangegate.com
127.0.0.1 adexchangeprediction.com
127.0.0.1 adexcite.com
127.0.0.1 adexpose.com
127.0.0.1 adext.inkclub.com
127.0.0.1 ad.f1cd.ru
127.0.0.1 adfactor.nl.invalid
127.0.0.1 adfarm.mediaplex.com
127.0.0.1 adflight.com
127.0.0.1 ad.flurry.com
127.0.0.1 adf.ly
127.0.0.1 adforce.com
127.0.0.1 adform.com
127.0.0.1 adformdsp.net
127.0.0.1 adform.net
127.0.0.1 ad.foxnetworks.com
127.0.0.1 ad.freecity.de
127.0.0.1 adgardener.com
127.0.0.1 ad.gate24.ch
127.0.0.1 ad.globe7.com
127.0.0.1 adgoto.com
127.0.0.1 ad.grafika.cz
127.0.0.1 adgridwork.com
127.0.0.1 ad.hbv.de
127.0.0.1 adhese.be
127.0.0.1 adhese.com
127.0.0.1 ad.hodomobile.com
127.0.0.1 ad.httpool.com
127.0.0.1 ad.hyena.cz
127.0.0.1 ad.iinfo.cz
127.0.0.1 ad.ilove.ch
127.0.0.1 adimage.asiaone.com.sg
127.0.0.1 adimage.guardian.co.uk
127.0.0.1 adimages.been.com
127.0.0.1 adimages.carsoup.com
127.0.0.1 adimages.go.com
127.0.0.1 adimages.homestore.com
127.0.0.1 adimages.omroepzeeland.nl
127.0.0.1 adimages.sanomawsoy.fi
127.0.0.1 adimg1.chosun.com
127.0.0.1 adimg.cnet.com
127.0.0.1 adimg.com.com
127.0.0.1 adimgs.sapo.pt
127.0.0.1 adimg.uimserv.net
127.0.0.1 adimpact.com
127.0.0.1 adincube.com
127.0.0.1 ad.infoseek.com
127.0.0.1 adinjector.net
127.0.0.1 adinterax.com
127.0.0.1 adisfy.com
127.0.0.1 adition.com
127.0.0.1 adition.de
127.0.0.1 adition.net
127.0.0.1 adizio.com
127.0.0.1 ad.jamba.net
127.0.0.1 ad.jamster.co.uk
127.0.0.1 ad.jetsoftware.com
127.0.0.1 adjix.com
127.0.0.1 adjug.com
127.0.0.1 adjuggler.com
127.0.0.1 adjuggler.yourdictionary.com
127.0.0.1 adjustnetwork.com
127.0.0.1 adk2ads.tictacti.com
127.0.0.1 adk2.com
127.0.0.1 ad.keenspace.com
127.0.0.1 adland.ru
127.0.0.1 adlantic.nl
127.0.0.1 ad.leadbolt.net
127.0.0.1 adledge.com
127.0.0.1 adlegend.com
127.0.0.1 ad.liveinternet.ru
127.0.0.1 adlog.com.com
127.0.0.1 adloox.com
127.0.0.1 adlooxtracking.com
127.0.0.1 ad.lupa.cz
127.0.0.1 adlure.net
127.0.0.1 admagnet.net
127.0.0.1 admailtiser.com
127.0.0.1 admanagement.ch
127.0.0.1 admanager.btopenworld.com
127.0.0.1 admanager.carsoup.com
127.0.0.1 adman.gr
127.0.0.1 adman.in.gr
127.0.0.1 adman.otenet.gr
127.0.0.1 admarketplace.net
127.0.0.1 admarvel.com
127.0.0.1 admax.nexage.com
127.0.0.1 admedia.com
127.0.0.1 admedia.ro
127.0.0.1 ad.media-servers.net
127.0.0.1 ad.mediastorm.hu
127.0.0.1 admeld.com
127.0.0.1 admerize.be
127.0.0.1 admeta.com
127.0.0.1 admex.com
127.0.0.1 ad.mgd.de
127.0.0.1 adminder.com
127.0.0.1 adminshop.com
127.0.0.1 admized.com
127.0.0.1 admob.com
127.0.0.1 admonitor.com
127.0.0.1 admotion.com.ar
127.0.0.1 ad.musicmatch.com
127.0.0.1 ad.nachtagenten.de
127.0.0.1 adnet.asahi.com
127.0.0.1 adnet.biz
127.0.0.1 adnet.de
127.0.0.1 adnetinteractive.com
127.0.0.1 adnet-media.net
127.0.0.1 adnet.ru
127.0.0.1 adnetwork.net
127.0.0.1 adnetworkperformance.com
127.0.0.1 adnet.worldreviewer.com
127.0.0.1 adnews.maddog2000.de
127.0.0.1 adnotch.com
127.0.0.1 ad.nozonedata.com
127.0.0.1 ad.nttnavi.co.jp
127.0.0.1 ad.nwt.cz
127.0.0.1 adnxs.com
127.0.0.1 adocean.pl
127.0.0.1 ad.onad.eu
127.0.0.1 adonspot.com
127.0.0.1 adoperator.com
127.0.0.1 adorigin.com
127.0.0.1 ad.pandora.tv
127.0.0.1 ad-pay.de
127.0.0.1 adpenguin.biz
127.0.0.1 adpepper.dk
127.0.0.1 adpepper.nl
127.0.0.1 adperium.com
127.0.0.1 adpia.vn
127.0.0.1 adplus.co.id
127.0.0.1 adplxmd.com
127.0.0.1 ad.preferances.com
127.0.0.1 adprofile.net
127.0.0.1 ad.profiwin.de
127.0.0.1 adprojekt.pl
127.0.0.1 ad.prv.pl
127.0.0.1 adq.nextag.com
127.0.0.1 ad.rambler.ru
127.0.0.1 adrazzi.com
127.0.0.1 adreactor.com
127.0.0.1 adreclaim.com
127.0.0.1 adrecreate.com
127.0.0.1 adremedy.com
127.0.0.1 adreporting.com
127.0.0.1 adres.internet.com
127.0.0.1 ad.reunion.com
127.0.0.1 adrevolver.com
127.0.0.1 adriver.ru
127.0.0.1 adrolays.de
127.0.0.1 adrotate.de
127.0.0.1 ad-rotator.com
127.0.0.1 adrotator.se
127.0.0.1 adrotic.girlonthenet.com
127.0.0.1 adrta.com
127.0.0.1 ads03.redtube.com
127.0.0.1 ads10.speedbit.com
127.0.0.1 ads180.com
127.0.0.1 ads1.canoe.ca
127.0.0.1 ads1.mediacapital.pt
127.0.0.1 ads1.msn.com
127.0.0.1 ads1.rne.com
127.0.0.1 ads1.virtual-nights.com
127.0.0.1 ads2004.treiberupdate.de
127.0.0.1 ads2.brazzers.com
127.0.0.1 ads2.clearchannel.com
127.0.0.1 ads2.contentabc.com
127.0.0.1 ads2.gamecity.net
127.0.0.1 ads2.jubii.dk
127.0.0.1 ads2.net-communities.co.uk
127.0.0.1 ads2.oneplace.com
127.0.0.1 ads2.rne.com
127.0.0.1 ads2.virtual-nights.com
127.0.0.1 ads2.xnet.cz
127.0.0.1 ads3.contentabc.com
127.0.0.1 ads3.gamecity.net
127.0.0.1 ads3.virtual-nights.com
127.0.0.1 ads4.clearchannel.com
127.0.0.1 ads4.gamecity.net
127.0.0.1 ads4homes.com
127.0.0.1 ads.4tube.com
127.0.0.1 ads4.virtual-nights.com
127.0.0.1 ads5.canoe.ca
127.0.0.1 ads.5ci.lt
127.0.0.1 ads5.virtual-nights.com
127.0.0.1 ads6.gamecity.net
127.0.0.1 ads7.gamecity.net
127.0.0.1 ads8.com
127.0.0.1 ads.abovetopsecret.com
127.0.0.1 ads.aceweb.net
127.0.0.1 ads.activestate.com
127.0.0.1 ads.adfox.ru
127.0.0.1 ads.administrator.de
127.0.0.1 ads.adshareware.net
127.0.0.1 ads.adultfriendfinder.com
127.0.0.1 ads.adultswim.com
127.0.0.1 ads.advance.net
127.0.0.1 ads.adverline.com
127.0.0.1 adsafeprotected.com
127.0.0.1 ads.affiliates.match.com
127.0.0.1 ads.ak.facebook.com.edgesuite.net
127.0.0.1 ads.allvatar.com
127.0.0.1 ads.alt.com
127.0.0.1 ads.amdmb.com
127.0.0.1 ads.amigos.com
127.0.0.1 ads.aol.com
127.0.0.1 ads.aol.co.uk
127.0.0.1 ads.apn.co.nz
127.0.0.1 ads.appsgeyser.com
127.0.0.1 ads.as4x.tmcs.net
127.0.0.1 ads.as4x.tmcs.ticketmaster.com
127.0.0.1 ads.asia1.com.sg
127.0.0.1 ads.asiafriendfinder.com
127.0.0.1 ads.ask.com
127.0.0.1 ads.aspalliance.com
127.0.0.1 Adsatt.ABCNews.starwave.com
127.0.0.1 adsatt.abc.starwave.com
127.0.0.1 adsatt.espn.go.com
127.0.0.1 adsatt.espn.starwave.com
127.0.0.1 Adsatt.go.starwave.com
127.0.0.1 ads.avazu.net
127.0.0.1 ads.batpmturner.com
127.0.0.1 ads.beenetworks.net
127.0.0.1 ads.belointeractive.com
127.0.0.1 ads.berlinonline.de
127.0.0.1 ads.betanews.com
127.0.0.1 ads.betfair.com
127.0.0.1 ads.betfair.com.au
127.0.0.1 ads.bigchurch.com
127.0.0.1 ads.bigfoot.com
127.0.0.1 ads.bing.com
127.0.0.1 ads.bittorrent.com
127.0.0.1 ads.blog.com
127.0.0.1 ads.bloomberg.com
127.0.0.1 ads.bluelithium.com
127.0.0.1 ads.bluemountain.com
127.0.0.1 ads.bluesq.com
127.0.0.1 ads.bonniercorp.com
127.0.0.1 ads.boylesports.com
127.0.0.1 ads.brabys.com
127.0.0.1 ads.brazzers.com
127.0.0.1 ads.bumq.com
127.0.0.1 ads.businessweek.com
127.0.0.1 adsby.bidtheatre.com
127.0.0.1 adscale.de
127.0.0.1 ads.canalblog.com
127.0.0.1 ads.canoe.ca
127.0.0.1 ads.casinocity.com
127.0.0.1 ads.cbc.ca
127.0.0.1 ads.cc
127.0.0.1 ads.cc-dt.com
127.0.0.1 ads.centraliprom.com
127.0.0.1 ads.cgnetworks.com
127.0.0.1 ads.channel4.com
127.0.0.1 adscholar.com
127.0.0.1 adscience.nl
127.0.0.1 ads.clearchannel.com
127.0.0.1 ads-click.com
127.0.0.1 ads.co.com
127.0.0.1 ads.com.com
127.0.0.1 ads.contactmusic.com
127.0.0.1 ads.contentabc.com
127.0.0.1 ads.contextweb.com
127.0.0.1 adscpm.com
127.0.0.1 ads.crakmedia.com
127.0.0.1 ads.creativematch.com
127.0.0.1 ads.creative-serving.com
127.0.0.1 ads.cricbuzz.com
127.0.0.1 ads.cybersales.cz
127.0.0.1 ads.dada.it
127.0.0.1 adsdaq.com
127.0.0.1 ads.datinggold.com
127.0.0.1 ads.datingyes.com
127.0.0.1 ads.dazoot.ro
127.0.0.1 ads.deltha.hu
127.0.0.1 ads.dennisnet.co.uk
127.0.0.1 ads.desmoinesregister.com
127.0.0.1 ads.detelefoongids.nl
127.0.0.1 ads.deviantart.com
127.0.0.1 ads.digital-digest.com
127.0.0.1 ads.digitalmedianet.com
127.0.0.1 ads.digitalpoint.com
127.0.0.1 ads.directionsmag.com
127.0.0.1 adsdk.com
127.0.0.1 ads.domain.com
127.0.0.1 ads.domeus.com
127.0.0.1 ads.eagletribune.com
127.0.0.1 ads.easy-forex.com
127.0.0.1 ads.eatinparis.com
127.0.0.1 ads.economist.com
127.0.0.1 ads.edbindex.dk
127.0.0.1 ads.egrana.com.br
127.0.0.1 ads.einmedia.com
127.0.0.1 ads.electrocelt.com
127.0.0.1 ads.elitetrader.com
127.0.0.1 ads.emirates.net.ae
127.0.0.1 adsend.de
127.0.0.1 ad.sensismediasmart.com.au
127.0.0.1 ads.epltalk.com
127.0.0.1 adserve.ams.rhythmxchange.com
127.0.0.1 adserver01.de
127.0.0.1 adserver1.backbeatmedia.com
127.0.0.1 adserver1-images.backbeatmedia.com
127.0.0.1 adserver1.mindshare.de
127.0.0.1 adserver1.ogilvy-interactive.de
127.0.0.1 adserver2.mindshare.de
127.0.0.1 adserver.43plc.com
127.0.0.1 adserver.71i.de
127.0.0.1 adserver.adultfriendfinder.com
127.0.0.1 adserver.aidameter.com
127.0.0.1 adserver.aol.fr
127.0.0.1 adserver.betandwin.de
127.0.0.1 adserver.bing.com
127.0.0.1 adserver.bizhat.com
127.0.0.1 adserver.break-even.it
127.0.0.1 adserver.cams.com
127.0.0.1 adserver.com
127.0.0.1 adserver.digitoday.com
127.0.0.1 adserver.dotcommedia.de
127.0.0.1 adserver.finditquick.com
127.0.0.1 adserver.flossiemediagroup.com
127.0.0.1 adserver.freecity.de
127.0.0.1 adserver.friendfinder.com
127.0.0.1 ad-server.gulasidorna.se
127.0.0.1 adserver.hardsextube.com
127.0.0.1 adserver.hardwareanalysis.com
127.0.0.1 adserver.html.it
127.0.0.1 adserver.hwupgrade.it
127.0.0.1 adserver.irishwebmasterforum.com
127.0.0.1 adserver.janes.com
127.0.0.1 adserver.libero.it
127.0.0.1 adserver.news.com.au
127.0.0.1 adserver.ngz-network.de
127.0.0.1 adserver.nydailynews.com
127.0.0.1 adserver.o2.pl
127.0.0.1 adserver.oddschecker.com
127.0.0.1 adserver.omroepzeeland.nl
127.0.0.1 ad-serverparc.nl
127.0.0.1 adserver.pl
127.0.0.1 adserverplus.com
127.0.0.1 adserver.portalofevil.com
127.0.0.1 adserver.portugalmail.net
127.0.0.1 adserver.portugalmail.pt
127.0.0.1 adserver.sanomawsoy.fi
127.0.0.1 adserver.sciflicks.com
127.0.0.1 adserver.sharewareonline.com
127.0.0.1 adserversolutions.com
127.0.0.1 adserver.spankaway.com
127.0.0.1 adserver.startnow.com
127.0.0.1 adserver.theonering.net
127.0.0.1 adserver.twitpic.com
127.0.0.1 adserver.viagogo.com
127.0.0.1 adserver.virginmedia.com
127.0.0.1 adserver.yahoo.com
127.0.0.1 adserv.evo-x.de
127.0.0.1 adserv.gamezone.de
127.0.0.1 adserv.iafrica.com
127.0.0.1 adservinginternational.com
127.0.0.1 adserving.unibet.com
127.0.0.1 ads.eu.msn.com
127.0.0.1 ads.exactdrive.com
127.0.0.1 ads.expat-blog.biz
127.0.0.1 ads.expedia.com
127.0.0.1 ad.seznam.cz
127.0.0.1 adsfac.eu
127.0.0.1 adsfac.net
127.0.0.1 ads.factorymedia.com
127.0.0.1 adsfac.us
127.0.0.1 ads.fairfax.com.au
127.0.0.1 ads.faxo.com
127.0.0.1 ads.ferianc.com
127.0.0.1 ads.filmup.com
127.0.0.1 ads.financialcontent.com
127.0.0.1 ads.flooble.com
127.0.0.1 ads.fool.com
127.0.0.1 ads.footymad.net
127.0.0.1 ads.forbes.com
127.0.0.1 ads.forbes.net
127.0.0.1 ads.forium.de
127.0.0.1 ads.fortunecity.com
127.0.0.1 ads.fotosidan.se
127.0.0.1 ads.foxkidseurope.net
127.0.0.1 ads.foxnetworks.com
127.0.0.1 ads.foxnews.com
127.0.0.1 ads.freecity.de
127.0.0.1 ads.friendfinder.com
127.0.0.1 ads.ft.com
127.0.0.1 ads.futurenet.com
127.0.0.1 ads.gamecity.net
127.0.0.1 ads.gamershell.com
127.0.0.1 ads.gamespyid.com
127.0.0.1 ads.gamigo.de
127.0.0.1 ads.gaming-universe.de
127.0.0.1 ads.gawker.com
127.0.0.1 ads.geekswithblogs.net
127.0.0.1 ads.glispa.com
127.0.0.1 ads.gmodules.com
127.0.0.1 ads.goyk.com
127.0.0.1 ads.gplusmedia.com
127.0.0.1 ads.gradfinder.com
127.0.0.1 ads.grindinggears.com
127.0.0.1 ads.groundspeak.com
127.0.0.1 ads.gsm-exchange.com
127.0.0.1 ads.gsmexchange.com
127.0.0.1 ads.guardian.co.uk
127.0.0.1 ads.guardianunlimited.co.uk
127.0.0.1 ads.guru3d.com
127.0.0.1 ads.hardwaresecrets.com
127.0.0.1 ads.harpers.org
127.0.0.1 ads.hbv.de
127.0.0.1 ads.hearstmags.com
127.0.0.1 ads.heartlight.org
127.0.0.1 ads.heias.com
127.0.0.1 ads.hideyourarms.com
127.0.0.1 ads.hollywood.com
127.0.0.1 ads.horsehero.com
127.0.0.1 ads.horyzon-media.com
127.0.0.1 adshost1.com
127.0.0.1 ads.iafrica.com
127.0.0.1 ads.ibest.com.br
127.0.0.1 ads.ibryte.com
127.0.0.1 ads.icq.com
127.0.0.1 adside.com
127.0.0.1 ads.ign.com
127.0.0.1 ad.simgames.net
127.0.0.1 ads.img.co.za
127.0.0.1 ads.imgur.com
127.0.0.1 ads.indiatimes.com
127.0.0.1 ads.infi.net
127.0.0.1 ads.internic.co.il
127.0.0.1 ads.ipowerweb.com
127.0.0.1 ads.isoftmarketing.com
127.0.0.1 ads.itv.com
127.0.0.1 ads.iwon.com
127.0.0.1 ads.jewishfriendfinder.com
127.0.0.1 ads.jiwire.com
127.0.0.1 ads.jobsite.co.uk
127.0.0.1 ads.jpost.com
127.0.0.1 ads.jubii.dk
127.0.0.1 ads.justhungry.com
127.0.0.1 adsk2.co
127.0.0.1 ads.kaktuz.net
127.0.0.1 adskape.ru
127.0.0.1 ads.kelbymediagroup.com
127.0.0.1 ads.kinobox.cz
127.0.0.1 ads.kinxxx.com
127.0.0.1 adsklick.de
127.0.0.1 ads.kompass.com
127.0.0.1 ads.krawall.de
127.0.0.1 ads.lesbianpersonals.com
127.0.0.1 ads.linkedin.com
127.0.0.1 ads.linuxfoundation.org
127.0.0.1 ads.linuxjournal.com
127.0.0.1 ads.linuxsecurity.com
127.0.0.1 ads.livenation.com
127.0.0.1 ad.slutload.com
127.0.0.1 ads.mariuana.it
127.0.0.1 adsmarket.com
127.0.0.1 ad.smartclip.net
127.0.0.1 adsmart.com
127.0.0.1 adsmart.co.uk
127.0.0.1 adsmart.net
127.0.0.1 ads.massinfra.nl
127.0.0.1 ads.mcafee.com
127.0.0.1 ads.mediaodyssey.com
127.0.0.1 ads.medienhaus.de
127.0.0.1 ads.mgnetwork.com
127.0.0.1 ads.mmania.com
127.0.0.1 ads.moceanads.com
127.0.0.1 adsmogo.com
127.0.0.1 ads.motor-forum.nl
127.0.0.1 ads.motormedia.nl
127.0.0.1 ads.msn.com
127.0.0.1 ads.multimania.lycos.fr
127.0.0.1 ads.nationalgeographic.com
127.0.0.1 adsnative.com
127.0.0.1 ads.ncm.com
127.0.0.1 ads.netmechanic.com
127.0.0.1 ads.networksolutions.com
127.0.0.1 ads.newdream.net
127.0.0.1 ads.newgrounds.com
127.0.0.1 ads.newmedia.cz
127.0.0.1 ads.newsint.co.uk
127.0.0.1 ads.newsquest.co.uk
127.0.0.1 ads.ninemsn.com.au
127.0.0.1 ads.nj.com
127.0.0.1 ads.nola.com
127.0.0.1 ads.nordichardware.com
127.0.0.1 ads.nordichardware.se
127.0.0.1 ads.nwsource.com
127.0.0.1 ads.nyi.net
127.0.0.1 ads.nytimes.com
127.0.0.1 ads.nyx.cz
127.0.0.1 ads.nzcity.co.nz
127.0.0.1 ads.o2.pl
127.0.0.1 ads.oddschecker.com
127.0.0.1 adsoftware.com
127.0.0.1 ads.okcimg.com
127.0.0.1 adsoldier.com
127.0.0.1 ads.ole.com
127.0.0.1 ads.olivebrandresponse.com
127.0.0.1 adsonar.com
127.0.0.1 ads.oneplace.com
127.0.0.1 ads.optusnet.com.au
127.0.0.1 ad-souk.com
127.0.0.1 ads.outpersonals.com
127.0.0.1 ad-space.net
127.0.0.1 adspace.ro
127.0.0.1 ads.passion.com
127.0.0.1 adspeed.net
127.0.0.1 ads.pennet.com
127.0.0.1 ads.penny-arcade.com
127.0.0.1 ads.phpclasses.org
127.0.0.1 ads.pickmeup-ltd.com
127.0.0.1 adspirit.de
127.0.0.1 ads.planet.nl
127.0.0.1 ads.pni.com
127.0.0.1 ads.pof.com
127.0.0.1 adsponse.de
127.0.0.1 ads.powweb.com
127.0.0.1 ads.primissima.it
127.0.0.1 ads.printscr.com
127.0.0.1 ads.prisacom.com
127.0.0.1 ads.program3.com
127.0.0.1 ads.psd2html.com
127.0.0.1 ads.pushplay.com
127.0.0.1 ads.quoka.de
127.0.0.1 ads.rcs.it
127.0.0.1 ads.recoletos.es
127.0.0.1 ads.rediff.com
127.0.0.1 ads.redlightcenter.com
127.0.0.1 ads.redtube.com
127.0.0.1 adsremote.scrippsnetworks.com
127.0.0.1 ads.resoom.de
127.0.0.1 ads.returnpath.net
127.0.0.1 adsrevenue.net
127.0.0.1 adsrv.deviantart.com
127.0.0.1 adsrv.eacdn.com
127.0.0.1 adsrv.iol.co.za
127.0.0.1 adsrvr.org
127.0.0.1 ads.s3.sitepoint.com
127.0.0.1 ads.satyamonline.com
127.0.0.1 ads.savannahnow.com
127.0.0.1 ads.saymedia.com
127.0.0.1 ads.scifi.com
127.0.0.1 ads.seniorfriendfinder.com
127.0.0.1 ads.servebom.com
127.0.0.1 ads.sexinyourcity.com
127.0.0.1 ads.shizmoo.com
127.0.0.1 ads.shopstyle.com
127.0.0.1 ads.sift.co.uk
127.0.0.1 ads.silverdisc.co.uk
127.0.0.1 ads.slim.com
127.0.0.1 ads.smartclick.com
127.0.0.1 ads.soft32.com
127.0.0.1 ads.space.com
127.0.0.1 ads.sptimes.com
127.0.0.1 ads.stackoverflow.com
127.0.0.1 adsstat.com
127.0.0.1 ads.sun.com
127.0.0.1 ads.supplyframe.com
127.0.0.1 ads.tahono.com
127.0.0.1 adstat.4u.pl
127.0.0.1 ads.techtv.com
127.0.0.1 ads.telegraph.co.uk
127.0.0.1 adstest.weather.com
127.0.0.1 ads.themovienation.com
127.0.0.1 ads.thestar.com
127.0.0.1 ads.tmcs.net
127.0.0.1 ads.t-online.de
127.0.0.1 ads.totallyfreestuff.com
127.0.0.1 ads.townhall.com
127.0.0.1 ads.trinitymirror.co.uk
127.0.0.1 ads.tripod.com
127.0.0.1 ads.tripod.lycos.co.uk
127.0.0.1 ads.tripod.lycos.de
127.0.0.1 ads.tripod.lycos.es
127.0.0.1 ads.tripod.lycos.it
127.0.0.1 ads.tripod.lycos.nl
127.0.0.1 ads.tripod.spray.se
127.0.0.1 ads.tso.dennisnet.co.uk
127.0.0.1 ads.twitter.com
127.0.0.1 ads.uknetguide.co.uk
127.0.0.1 ads.ultimate-guitar.com
127.0.0.1 ads.uncrate.com
127.0.0.1 ads.undertone.com
127.0.0.1 adsupply.com
127.0.0.1 ads.usatoday.com
127.0.0.1 ads.v3.com
127.0.0.1 ads.verticalresponse.com
127.0.0.1 ads.vgchartz.com
127.0.0.1 ads.videobash.com
127.0.0.1 ads.videosz.com
127.0.0.1 ads.virtualcountries.com
127.0.0.1 ads.virtual-nights.com
127.0.0.1 ads.vnumedia.com
127.0.0.1 ads.waps.cn
127.0.0.1 ads.wapx.cn
127.0.0.1 ads.weather.ca
127.0.0.1 ads.web.aol.com
127.0.0.1 ads.web.cs.com
127.0.0.1 ads.web.de
127.0.0.1 ads.webmasterpoint.org
127.0.0.1 ads.websiteservices.com
127.0.0.1 ads.whi.co.nz
127.0.0.1 ads.whoishostingthis.com
127.0.0.1 ads.wiezoekje.nl
127.0.0.1 ads.wikia.nocookie.net
127.0.0.1 ads.wineenthusiast.com
127.0.0.1 adswizz.com
127.0.0.1 ads.wwe.biz
127.0.0.1 ads.xhamster.com
127.0.0.1 ads.xtra.co.nz
127.0.0.1 ads.y-0.net
127.0.0.1 ads.yahoo.com
127.0.0.1 ads.yimg.com
127.0.0.1 ads.yldmgrimg.net
127.0.0.1 adsymptotic.com
127.0.0.1 adsynergy.com
127.0.0.1 ads.yourfreedvds.com
127.0.0.1 ads.youtube.com
127.0.0.1 adsystem.simplemachines.org
127.0.0.1 adsys.townnews.com
127.0.0.1 ads.zdnet.com
127.0.0.1 ads.ztod.com
127.0.0.1 ad.tbn.ru
127.0.0.1 ad-tech.com
127.0.0.1 adtech.de
127.0.0.1 ad.technoratimedia.com
127.0.0.1 adtechus.com
127.0.0.1 adtegrity.net
127.0.0.1 ad.thewheelof.com
127.0.0.1 adthis.com
127.0.0.1 adtiger.de
127.0.0.1 adtoll.com
127.0.0.1 adtology.com
127.0.0.1 adtoma.com
127.0.0.1 adtrace.org
127.0.0.1 adtrade.net
127.0.0.1 adtrading.de
127.0.0.1 adtrak.net
127.0.0.1 adtriplex.com
127.0.0.1 ad.turn.com
127.0.0.1 ad.tv2.no
127.0.0.1 ad.twitchguru.com
127.0.0.1 adultadvertising.com
127.0.0.1 ad-up.com
127.0.0.1 ad.usatoday.com
127.0.0.1 adv-adserver.com
127.0.0.1 advariant.com
127.0.0.1 adv-banner.libero.it
127.0.0.1 adv.cooperhosting.net
127.0.0.1 adventory.com
127.0.0.1 advert.bayarea.com
127.0.0.1 advert.dyna.ultraweb.hu
127.0.0.1 adverticum.com
127.0.0.1 adverticum.net
127.0.0.1 adverticus.de
127.0.0.1 advertise.com
127.0.0.1 advertiseireland.com
127.0.0.1 advertiserurl.com
127.0.0.1 advertisespace.com
127.0.0.1 advertisingbanners.com
127.0.0.1 advertisingbox.com
127.0.0.1 advertising.com
127.0.0.1 advertising.guildlaunch.net
127.0.0.1 advertisingtag.net
127.0.0.1 advertmarket.com
127.0.0.1 advertmedia.de
127.0.0.1 advertpro.sitepoint.com
127.0.0.1 advertpro.ya.com
127.0.0.1 adverts.carltononline.com
127.0.0.1 advertserve.com
127.0.0.1 advertstream.com
127.0.0.1 advertwizard.com
127.0.0.1 adv.freeonline.it
127.0.0.1 advfromnwl.com
127.0.0.1 adv.hwupgrade.it
127.0.0.1 advideo.uimserv.net
127.0.0.1 adview.ppro.de
127.0.0.1 ad.virtual-nights.com
127.0.0.1 advisormedia.cz
127.0.0.1 adviva.net
127.0.0.1 adv.livedoor.com
127.0.0.1 adv.nexthardware.com
127.0.0.1 advnt.com
127.0.0.1 adv.webmd.com
127.0.0.1 adv.wp.pl
127.0.0.1 adv.yo.cz
127.0.0.1 adwareremovergold.com
127.0.0.1 ad.wavu.hu
127.0.0.1 ad.way.cz
127.0.0.1 ad.weatherbug.com
127.0.0.1 adwhirl.com
127.0.0.1 adwitserver.com
127.0.0.1 adworldnetwork.com
127.0.0.1 adworx.at
127.0.0.1 adworx.be
127.0.0.1 adworx.nl
127.0.0.1 ad.wsod.com
127.0.0.1 ad.wz.cz
127.0.0.1 adx.allstar.cz
127.0.0.1 adx.atnext.com
127.0.0.1 adxpansion.com
127.0.0.1 adxpose.com
127.0.0.1 adxprts.com
127.0.0.1 ad.xrea.com
127.0.0.1 adxvalue.com
127.0.0.1 ad.yadro.ru
127.0.0.1 adyea.com
127.0.0.1 ad.yourmedia.com
127.0.0.1 adz2you.com
127.0.0.1 ad.zanox.com
127.0.0.1 adzbazar.com
127.0.0.1 adzerk.net
127.0.0.1 adzerk.s3.amazonaws.com
127.0.0.1 adzones.com
127.0.0.1 af-ad.co.uk
127.0.0.1 affbuzzads.com
127.0.0.1 affiliate.1800flowers.com
127.0.0.1 affiliate.doubleyourdating.com
127.0.0.1 affiliate.dtiserv.com
127.0.0.1 affiliatefuel.com
127.0.0.1 affiliatefuture.com
127.0.0.1 affiliate.gamestop.com
127.0.0.1 affiliate.mercola.com
127.0.0.1 affiliate.mogs.com
127.0.0.1 affiliate.offgamers.com
127.0.0.1 affiliates.allposters.com
127.0.0.1 affiliates.babylon.com
127.0.0.1 affiliates.digitalriver.com
127.0.0.1 affiliates.globat.com
127.0.0.1 affiliates.internationaljock.com
127.0.0.1 affiliates.streamray.com
127.0.0.1 affiliates.thinkhost.net
127.0.0.1 affiliates.thrixxx.com
127.0.0.1 affiliates.ultrahosting.com
127.0.0.1 affiliatetracking.com
127.0.0.1 affiliatetracking.net
127.0.0.1 affiliate.travelnow.com
127.0.0.1 affiliate.viator.com
127.0.0.1 affiliatewindow.com
127.0.0.1 affiliation-france.com
127.0.0.1 affili.net
127.0.0.1 afftracking.justanswer.com
127.0.0.1 agreemand.com
127.0.0.1 ahalogy.com
127.0.0.1 ah-ha.com
127.0.0.1 aidu-ads.de
127.0.0.1 aim4media.com
127.0.0.1 aistat.net
127.0.0.1 aktrack.pubmatic.com
127.0.0.1 alclick.com
127.0.0.1 alenty.com
127.0.0.1 alexa-sitestats.s3.amazonaws.com
127.0.0.1 alipromo.com
127.0.0.1 all4spy.com
127.0.0.1 alladvantage.com
127.0.0.1 allosponsor.com
127.0.0.1 amazingcounters.com
127.0.0.1 amazon-adsystem.com
127.0.0.1 ambitiousagreement.com
127.0.0.1 americash.com
127.0.0.1 a.mktw.net
127.0.0.1 amung.us
127.0.0.1 anahtars.com
127.0.0.1 analytics.adpost.org
127.0.0.1 analytics.google.com
127.0.0.1 analytics.live.com
127.0.0.1 analytics.yahoo.com
127.0.0.1 anm.intelli-direct.com
127.0.0.1 annonser.dagbladet.no
127.0.0.1 an.tacoda.net
127.0.0.1 anxiousapples.com
127.0.0.1 api.intensifier.de
127.0.0.1 app.adblockhyper.us
127.0.0.1 appsflyer.com
127.0.0.1 apture.com
127.0.0.1 arc1.msn.com
127.0.0.1 arcadebanners.com
127.0.0.1 ard.xxxblackbook.com
127.0.0.1 are-ter.com
127.0.0.1 as1.advfn.com
127.0.0.1 a.sakh.com
127.0.0.1 assets1.exgfnetwork.com
127.0.0.1 assoc-amazon.com
127.0.0.1 as.webmd.com
127.0.0.1 at-adserver.alltop.com
127.0.0.1 atdmt.com
127.0.0.1 athena-ads.wikia.com
127.0.0.1 atwola.com
127.0.0.1 a.ucoz.net
127.0.0.1 a.ucoz.ru
127.0.0.1 auctionads.com
127.0.0.1 auctionads.net
127.0.0.1 audience2media.com
127.0.0.1 audit.median.hu
127.0.0.1 audit.webinform.hu
127.0.0.1 auto-bannertausch.de
127.0.0.1 autohits.dk
127.0.0.1 avenuea.com
127.0.0.1 avpa.javalobby.org
127.0.0.1 avres.net
127.0.0.1 avsads.com
127.0.0.1 avzadsrv.com
127.0.0.1 awempire.com
127.0.0.1 awin1.com
127.0.0.1 a.xanga.com
127.0.0.1 azfront.com
127.0.0.1 b0b1o.bid
127.0.0.1 b-1st.com
127.0.0.1 ba.afl.rakuten.co.jp
127.0.0.1 babs.tv2.dk
127.0.0.1 backbeatmedia.com
127.0.0.1 banik.redigy.cz
127.0.0.1 banner.ad.nu
127.0.0.1 bannerads.de
127.0.0.1 banner.ambercoastcasino.com
127.0.0.1 banner.blogranking.net
127.0.0.1 bannerboxes.com
127.0.0.1 banner.buempliz-online.ch
127.0.0.1 banner.casinodelrio.com
127.0.0.1 banner.casino.net
127.0.0.1 bannercommunity.de
127.0.0.1 bannerconnect.com
127.0.0.1 bannerconnect.net
127.0.0.1 banner.cotedazurpalace.com
127.0.0.1 banner.coza.com
127.0.0.1 banner.cz
127.0.0.1 banner.easyspace.com
127.0.0.1 banner.elisa.net
127.0.0.1 banner.eurogrand.com
127.0.0.1 banner-exchange-24.de
127.0.0.1 bannerexchange.cjb.net
127.0.0.1 bannerflow.com
127.0.0.1 banner.getgo.de
127.0.0.1 banner.goldenpalace.com
127.0.0.1 bannergrabber.internet.gr
127.0.0.1 bannerhost.com
127.0.0.1 bannerimage.com
127.0.0.1 banner.img.co.za
127.0.0.1 banner.inyourpocket.com
127.0.0.1 banner.kiev.ua
127.0.0.1 bannerlandia.com.ar
127.0.0.1 banner.linux.se
127.0.0.1 bannermall.com
127.0.0.1 bannermarkt.nl
127.0.0.1 banner.media-system.de
127.0.0.1 banner.mindshare.de
127.0.0.1 banner.nixnet.cz
127.0.0.1 banner.noblepoker.com
127.0.0.1 banner.northsky.com
127.0.0.1 banner.orb.net
127.0.0.1 banner.penguin.cz
127.0.0.1 bannerpower.com
127.0.0.1 banner.rbc.ru
127.0.0.1 banner.relcom.ru
127.0.0.1 banners.adultfriendfinder.com
127.0.0.1 banners.amigos.com
127.0.0.1 banners.asiafriendfinder.com
127.0.0.1 banners.audioholics.com
127.0.0.1 banners.babylon-x.com
127.0.0.1 banners.bol.com.br
127.0.0.1 banners.cams.com
127.0.0.1 banners.clubseventeen.com
127.0.0.1 banners.czi.cz
127.0.0.1 banners.dine.com
127.0.0.1 banners.direction-x.com
127.0.0.1 banners.directnic.com
127.0.0.1 banners.easydns.com
127.0.0.1 bannerserver.com
127.0.0.1 banners.freett.com
127.0.0.1 banners.friendfinder.com
127.0.0.1 banners.getiton.com
127.0.0.1 bannersgomlm.com
127.0.0.1 bannershotlink.perfectgonzo.com
127.0.0.1 banners.iq.pl
127.0.0.1 banners.isoftmarketing.com
127.0.0.1 banners.linkbuddies.com
127.0.0.1 bannersng.yell.com
127.0.0.1 bannerspace.com
127.0.0.1 banners.passion.com
127.0.0.1 banners.resultonline.com
127.0.0.1 banners.sexsearch.com
127.0.0.1 banners.sys-con.com
127.0.0.1 banners.thomsonlocal.com
127.0.0.1 banners.videosz.com
127.0.0.1 banners.virtuagirlhd.com
127.0.0.1 bannerswap.com
127.0.0.1 banners.wunderground.com
127.0.0.1 banner.tanto.de
127.0.0.1 bannertesting.com
127.0.0.1 banner.titan-dsl.de
127.0.0.1 banner.vadian.net
127.0.0.1 banner.webmersion.com
127.0.0.1 banner.wirenode.com
127.0.0.1 bannery.cz
127.0.0.1 bannieres.acces-contenu.com
127.0.0.1 bans.adserver.co.il
127.0.0.1 bans.bride.ru
127.0.0.1 b.aol.com
127.0.0.1 barnesandnoble.bfast.com
127.0.0.1 basebanner.com
127.0.0.1 baskettexture.com
127.0.0.1 bawdybeast.com
127.0.0.1 baypops.com
127.0.0.1 bbelements.com
127.0.0.1 bbn.img.com.ua
127.0.0.1 beamincrease.com
127.0.0.1 beamkite.com
127.0.0.1 begun.ru
127.0.0.1 belstat.com
127.0.0.1 belstat.nl
127.0.0.1 b.engadget.com
127.0.0.1 berp.com
127.0.0.1 best-pr.info
127.0.0.1 bestsearch.net
127.0.0.1 best-top.ro
127.0.0.1 bhclicks.com
127.0.0.1 bidclix.com
127.0.0.1 bidclix.net
127.0.0.1 bidswitch.net
127.0.0.1 bidtrk.com
127.0.0.1 bidvertiser.com
127.0.0.1 bigbangmedia.com
127.0.0.1 bigclicks.com
127.0.0.1 billboard.cz
127.0.0.1 bitads.net
127.0.0.1 bitmedianetwork.com
127.0.0.1 bizad.nikkeibp.co.jp
127.0.0.1 bizographics.com
127.0.0.1 bizrate.com
127.0.0.1 blast4traffic.com
127.0.0.1 blingbucks.com
127.0.0.1 blogads.com
127.0.0.1 blogcounter.de
127.0.0.1 blogherads.com
127.0.0.1 blogrush.com
127.0.0.1 blogtoplist.se
127.0.0.1 blogtopsites.com
127.0.0.1 blueadvertise.com
127.0.0.1 bluekai.com
127.0.0.1 bluelithium.com
127.0.0.1 bluewhaleweb.com
127.0.0.1 bm.annonce.cz
127.0.0.1 bn.bfast.com
127.0.0.1 boersego-ads.de
127.0.0.1 boilingbeetle.com
127.0.0.1 boldchat.com
127.0.0.1 boomads.com
127.0.0.1 boom.ro
127.0.0.1 boost-my-pr.de
127.0.0.1 box.anchorfree.net
127.0.0.1 bpath.com
127.0.0.1 braincash.com
127.0.0.1 brandreachsys.com
127.0.0.1 brassrule.com
127.0.0.1 bravenet.com.invalid
127.0.0.1 bridgetrack.com
127.0.0.1 brightinfo.com
127.0.0.1 british-banners.com
127.0.0.1 broadboundary.com
127.0.0.1 bs.yandex.ru
127.0.0.1 bttrack.com
127.0.0.1 budsinc.com
127.0.0.1 bullseye.backbeatmedia.com
127.0.0.1 buyhitscheap.com
127.0.0.1 buysellads.com
127.0.0.1 buzzonclick.com
127.0.0.1 bvalphaserver.com
127.0.0.1 bwp.download.com
127.0.0.1 c1exchange.com
127.0.0.1 c1.nowlinux.com
127.0.0.1 calmfoot.com
127.0.0.1 campaign.bharatmatrimony.com
127.0.0.1 caniamedia.com
127.0.0.1 carambo.la
127.0.0.1 carbonads.com
127.0.0.1 carbonads.net
127.0.0.1 casalemedia.com
127.0.0.1 casalmedia.com
127.0.0.1 cash4members.com
127.0.0.1 cash4popup.de
127.0.0.1 cashcrate.com
127.0.0.1 cashengines.com
127.0.0.1 cashfiesta.com
127.0.0.1 cashlayer.com
127.0.0.1 cashpartner.com
127.0.0.1 casinogames.com
127.0.0.1 casinopays.com
127.0.0.1 casinorewards.com
127.0.0.1 casinotraffic.com
127.0.0.1 casinotreasure.com
127.0.0.1 cbanners.virtuagirlhd.com
127.0.0.1 c.bigmir.net
127.0.0.1 cbmall.com
127.0.0.1 cdn.freefacti.com
127.0.0.1 cdn.freefarcy.com
127.0.0.1 cdn.segment.com
127.0.0.1 cecash.com
127.0.0.1 centerpointmedia.com
127.0.0.1 ceskydomov.alias.ngs.modry.cz
127.0.0.1 cetrk.com
127.0.0.1 cgicounter.puretec.de
127.0.0.1 chameleon.ad
127.0.0.1 channelintelligence.com
127.0.0.1 chartbeat.com
127.0.0.1 chartbeat.net
127.0.0.1 chart.dk
127.0.0.1 checkm8.com
127.0.0.1 checkstat.nl
127.0.0.1 cherrythread.com
127.0.0.1 chestionar.ro
127.0.0.1 chiefcurrent.com
127.0.0.1 chinchickens.com
127.0.0.1 chitika.net
127.0.0.1 ch.questionmarket.com
127.0.0.1 cibleclick.com.invalid
127.0.0.1 cityads.telus.net
127.0.0.1 cjbmanagement.com
127.0.0.1 cj.com
127.0.0.1 cjlog.com
127.0.0.1 claria.com
127.0.0.1 class-act-clicks.com
127.0.0.1 click2freemoney.com
127.0.0.1 click2paid.com
127.0.0.1 clickability.com
127.0.0.1 click.absoluteagency.com
127.0.0.1 clickadz.com
127.0.0.1 clickagents.com
127.0.0.1 clickbank.com
127.0.0.1 clickbank.net
127.0.0.1 clickbooth.com
127.0.0.1 clickboothlnk.com
127.0.0.1 clickbrokers.com
127.0.0.1 clickcompare.co.uk
127.0.0.1 clickdensity.com
127.0.0.1 clickedyclick.com
127.0.0.1 click.fool.com
127.0.0.1 clickhereforcellphones.com
127.0.0.1 clickhouse.com
127.0.0.1 clickhype.com
127.0.0.1 click.kmindex.ru
127.0.0.1 clicklink.jp
127.0.0.1 clickmedia.ro
127.0.0.1 clickonometrics.pl
127.0.0.1 clicks.equantum.com
127.0.0.1 clickserve.cc-dt.com
127.0.0.1 clicks.mods.de
127.0.0.1 clicksor.com
127.0.0.1 clicktag.de
127.0.0.1 clickthruserver.com
127.0.0.1 clickthrutraffic.com
127.0.0.1 clicktrace.info
127.0.0.1 clicktracks.com
127.0.0.1 clicktrack.ziyu.net
127.0.0.1 clicktrade.com
127.0.0.1 clickxchange.com
127.0.0.1 clickz.com
127.0.0.1 clickzxc.com
127.0.0.1 clicmanager.fr
127.0.0.1 clientmetrics-pa.googleapis.com
127.0.0.1 clients.tbo.com
127.0.0.1 clikerz.net
127.0.0.1 cliksolution.com
127.0.0.1 clixgalore.com
127.0.0.1 clkads.com
127.0.0.1 clk.konflab.com
127.0.0.1 clkrev.com
127.0.0.1 cluster.adultworld.com
127.0.0.1 clustrmaps.com
127.0.0.1 cnomy.com
127.0.0.1 cnt1.pocitadlo.cz
127.0.0.1 cnt.spbland.ru
127.0.0.1 code-server.biz
127.0.0.1 coinhive.com
127.0.0.1 colonize.com
127.0.0.1 comclick.com
127.0.0.1 commandwalk.com
127.0.0.1 commindo-media-ressourcen.de
127.0.0.1 commissionmonster.com
127.0.0.1 compactbanner.com
127.0.0.1 comprabanner.it
127.0.0.1 concernrain.com
127.0.0.1 confirmed-profits.com
127.0.0.1 connextra.com
127.0.0.1 consciouscabbage.com
127.0.0.1 contaxe.de
127.0.0.1 content.acc-hd.de
127.0.0.1 content.ad
127.0.0.1 contextweb.com
127.0.0.1 conversantmedia.com
127.0.0.1 conversionruler.com
127.0.0.1 cookies.cmpnet.com
127.0.0.1 copperchickens.com
127.0.0.1 copycarpenter.com
127.0.0.1 copyrightaccesscontrols.com
127.0.0.1 coremetrics.com
127.0.0.1 counted.com
127.0.0.1 counter.bloke.com
127.0.0.1 counter.cnw.cz
127.0.0.1 counter.cz
127.0.0.1 counter.dreamhost.com
127.0.0.1 counter.fateback.com
127.0.0.1 counter.mirohost.net
127.0.0.1 counter.mojgorod.ru
127.0.0.1 counter.nowlinux.com
127.0.0.1 counter.rambler.ru
127.0.0.1 counter.search.bg
127.0.0.1 counters.honesty.com
127.0.0.1 counter.snackly.co
127.0.0.1 counter.sparklit.com
127.0.0.1 counter.yadro.ru
127.0.0.1 counting.kmindex.ru
127.0.0.1 count.rbc.ru
127.0.0.1 count.rin.ru
127.0.0.1 counts.tucows.com
127.0.0.1 count.west263.com
127.0.0.1 coupling-media.de
127.0.0.1 cp.abbp1.pw
127.0.0.1 cpalead.com
127.0.0.1 cpays.com
127.0.0.1 cpmaffiliation.com
127.0.0.1 cpmstar.com
127.0.0.1 cpxinteractive.com
127.0.0.1 cqcounter.com
127.0.0.1 crakmedia.com
127.0.0.1 craktraffic.com
127.0.0.1 crawlability.com
127.0.0.1 crawlclocks.com
127.0.0.1 crazypopups.com
127.0.0.1 creafi-online-media.com
127.0.0.1 creatives.as4x.tmcs.net
127.0.0.1 creatives.livejasmin.com
127.0.0.1 creative.whi.co.nz
127.0.0.1 credishe.com
127.0.0.1 crispads.com
127.0.0.1 criteo.com
127.0.0.1 critictruck.com
127.0.0.1 crowdgravity.com
127.0.0.1 crownclam.com
127.0.0.1 crtv.mate1.com
127.0.0.1 crwdcntrl.net
127.0.0.1 ctnetwork.hu
127.0.0.1 cubics.com
127.0.0.1 curtaincows.com
127.0.0.1 customad.cnn.com
127.0.0.1 cutecushion.com
127.0.0.1 cyberbounty.com
127.0.0.1 cybermonitor.com
127.0.0.1 d.adroll.com
127.0.0.1 dakic-ia-300.com
127.0.0.1 danban.com
127.0.0.1 dapper.net
127.0.0.1 datashreddergold.com
127.0.0.1 dbbsrv.com
127.0.0.1 dc-storm.com
127.0.0.1 de17a.com
127.0.0.1 dealdotcom.com
127.0.0.1 debtbusterloans.com
127.0.0.1 decisiveducks.com
127.0.0.1 decknetwork.net
127.0.0.1 delightdriving.com
127.0.0.1 deloo.de
127.0.0.1 deloton.com
127.0.0.1 demandbase.com
127.0.0.1 demdex.net
127.0.0.1 di1.shopping.com
127.0.0.1 dialerporn.com
127.0.0.1 dianomi.com
127.0.0.1 didtheyreadit.com
127.0.0.1 differentdesk.com
127.0.0.1 digital-ads.s3.amazonaws.com
127.0.0.1 digitalmerkat.com
127.0.0.1 directaclick.com
127.0.0.1 directivepub.com
127.0.0.1 directleads.com
127.0.0.1 directorym.com
127.0.0.1 directtrack.com
127.0.0.1 direct-xxx-access.com
127.0.0.1 discountclick.com
127.0.0.1 displayadsmedia.com
127.0.0.1 dist.belnk.com
127.0.0.1 dk4ywix.com
127.0.0.1 dmtracker.com
127.0.0.1 dmtracking2.alibaba.com
127.0.0.1 dmtracking.alibaba.com
127.0.0.1 dnads.directnic.com
127.0.0.1 docksalmon.com
127.0.0.1 domaining.in
127.0.0.1 domainsponsor.com
127.0.0.1 domainsteam.de
127.0.0.1 domdex.com
127.0.0.1 doubleclick.com
127.0.0.1 doubleclick.de
127.0.0.1 doubleclick.net
127.0.0.1 doublepimp.com
127.0.0.1 doubtfulrainstorm.com
127.0.0.1 dragzebra.com
127.0.0.1 drumcash.com
127.0.0.1 dynamic.fmpub.net
127.0.0.1 eadexchange.com
127.0.0.1 e-adimages.scrippsnetworks.com
127.0.0.1 eas.almamedia.fi
127.0.0.1 easyhits4u.com
127.0.0.1 e-bannerx.com
127.0.0.1 ebayadvertising.com
127.0.0.1 ebocornac.com
127.0.0.1 ebuzzing.com
127.0.0.1 ecircle-ag.com
127.0.0.1 eclick.vn
127.0.0.1 ecoupons.com
127.0.0.1 e-debtconsolidation.com
127.0.0.1 edgeio.com
127.0.0.1 effectivemeasure.com
127.0.0.1 effectivemeasure.net
127.0.0.1 eiv.baidu.com
127.0.0.1 e.kde.cz
127.0.0.1 elasticchange.com
127.0.0.1 elephantqueue.com
127.0.0.1 elitedollars.com
127.0.0.1 elitetoplist.com
127.0.0.1 emarketer.com
127.0.0.1 emediate.dk
127.0.0.1 emediate.eu
127.0.0.1 e-m.fr
127.0.0.1 engine.espace.netavenir.com
127.0.0.1 enginenetwork.com
127.0.0.1 enoratraffic.com
127.0.0.1 enquisite.com
127.0.0.1 entercasino.com
127.0.0.1 e-n-t-e-r-n-e-x.com
127.0.0.1 entrecard.s3.amazonaws.com
127.0.0.1 e-planning.net
127.0.0.1 eqads.com
127.0.0.1 ero-advertising.com
127.0.0.1 esellerate.net
127.0.0.1 estat.com
127.0.0.1 etahub.com
127.0.0.1 etargetnet.com
127.0.0.1 etracker.de
127.0.0.1 eu1.madsone.com
127.0.0.1 eu-adcenter.net
127.0.0.1 eur.a1.yimg.com
127.0.0.1 eurekster.com
127.0.0.1 euroclick.com
127.0.0.1 euros4click.de
127.0.0.1 eusta.de
127.0.0.1 evergage.com
127.0.0.1 evidencecleanergold.com
127.0.0.1 ewebcounter.com
127.0.0.1 exchangead.com
127.0.0.1 exchange.bg
127.0.0.1 exchangeclicksonline.com
127.0.0.1 exchange-it.com
127.0.0.1 exclusivebrass.com
127.0.0.1 exelator.com
127.0.0.1 exit76.com
127.0.0.1 exitexchange.com
127.0.0.1 exitfuel.com
127.0.0.1 exoclick.com
127.0.0.1 exogripper.com
127.0.0.1 experteerads.com
127.0.0.1 exponential.com
127.0.0.1 express-submit.de
127.0.0.1 extractorandburner.com
127.0.0.1 extreme-dm.com
127.0.0.1 extremetracking.com
127.0.0.1 eyeblaster.com
127.0.0.1 eyeota.net
127.0.0.1 eyereturn.com
127.0.0.1 eyeviewads.com
127.0.0.1 eyewonder.com
127.0.0.1 ezula.com
127.0.0.1 f5biz.com
127.0.0.1 fast-adv.it
127.0.0.1 fastclick.com
127.0.0.1 fastclick.com.edgesuite.net
127.0.0.1 fastclick.net
127.0.0.1 fc.webmasterpro.de
127.0.0.1 feedbackresearch.com
127.0.0.1 feedjit.com
127.0.0.1 ffxcam.fairfax.com.au
127.0.0.1 fimserve.com
127.0.0.1 findcommerce.com
127.0.0.1 findyourcasino.com
127.0.0.1 fineclicks.com
127.0.0.1 firstlightera.com
127.0.0.1 first.nova.cz
127.0.0.1 flashtalking.com
127.0.0.1 flavordecision.com
127.0.0.1 fleshlightcash.com
127.0.0.1 flexbanner.com
127.0.0.1 floodprincipal.com
127.0.0.1 flowgo.com
127.0.0.1 flurry.com
127.0.0.1 fonecta.leiki.com
127.0.0.1 foo.cosmocode.de
127.0.0.1 forex-affiliate.net
127.0.0.1 fpctraffic2.com
127.0.0.1 fpctraffic.com
127.0.0.1 fqtag.com
127.0.0.1 fragmentserv.iac-online.de
127.0.0.1 freebanner.com
127.0.0.1 free-banners.com
127.0.0.1 freelogs.com
127.0.0.1 freeonlineusers.com
127.0.0.1 freepay.com
127.0.0.1 freestats.com
127.0.0.1 freestats.tv
127.0.0.1 freewebcounter.com
127.0.0.1 functionalclam.com
127.0.0.1 funklicks.com
127.0.0.1 funpageexchange.com
127.0.0.1 fusionads.net
127.0.0.1 fusionquest.com
127.0.0.1 futuristicfairies.com
127.0.0.1 fuzzyflavor.com
127.0.0.1 fxstyle.net
127.0.0.1 ga87z2o.com
127.0.0.1 galaxien.com
127.0.0.1 game-advertising-online.com
127.0.0.1 gamehouse.com
127.0.0.1 gamesites100.net
127.0.0.1 gamesites200.com
127.0.0.1 gamesitestop100.com
127.0.0.1 gator.com
127.0.0.1 gbanners.hornymatches.com
127.0.0.1 gemius.pl
127.0.0.1 geobanner.adultfriendfinder.com
127.0.0.1 geo.digitalpoint.com
127.0.0.1 geovisite.com
127.0.0.1 getclicky.com
127.0.0.1 giddycoat.com
127.0.0.1 gigya.com.invalid
127.0.0.1 globalismedia.com
127.0.0.1 globaltakeoff.net
127.0.0.1 globaltrack.com.invalid
127.0.0.1 globe7.com
127.0.0.1 globus-inter.com
127.0.0.1 gmads.net
127.0.0.1 go-clicks.de
127.0.0.1 goingplatinum.com
127.0.0.1 goldstats.com
127.0.0.1 googleadservices.com
127.0.0.1 google-analytics.com
127.0.0.1 googlesyndication.com
127.0.0.1 go-rank.de
127.0.0.1 gorgeousground.com
127.0.0.1 gostats.com
127.0.0.1 gp.dejanews.com
127.0.0.1 gpr.hu
127.0.0.1 grafstat.ro
127.0.0.1 grapeshot.co.uk
127.0.0.1 greetzebra.com
127.0.0.1 greystripe.com
127.0.0.1 gtop100.com
127.0.0.1 guardedgovernor.com
127.0.0.1 guitarbelieve.com
127.0.0.1 gunggo.com
127.0.0.1 harrenmedia.com
127.0.0.1 harrenmedianetwork.com
127.0.0.1 havamedia.net
127.0.0.1 heias.com
127.0.0.1 hellobar.com
127.0.0.1 hentaicounter.com
127.0.0.1 herbalaffiliateprogram.com
127.0.0.1 hexusads.fluent.ltd.uk
127.0.0.1 heyos.com
127.0.0.1 hgads.com
127.0.0.1 hidden.gogoceleb.com
127.0.0.1 hightrafficads.com
127.0.0.1 hilariouszinc.com
127.0.0.1 histats.com
127.0.0.1 hit.bg
127.0.0.1 hitbox.com
127.0.0.1 hitcents.com
127.0.0.1 hitfarm.com
127.0.0.1 hitiz.com
127.0.0.1 hitlist.ru
127.0.0.1 hitlounge.com
127.0.0.1 hitometer.com
127.0.0.1 hit-parade.com
127.0.0.1 hits4me.com
127.0.0.1 hits4pay.com
127.0.0.1 hits.europuls.eu
127.0.0.1 hits.informer.com
127.0.0.1 hitslink.com
127.0.0.1 hits.puls.lv
127.0.0.1 hits.theguardian.com
127.0.0.1 hittail.com
127.0.0.1 hit.ua
127.0.0.1 hit.webcentre.lycos.co.uk
127.0.0.1 hollandbusinessadvertising.nl
127.0.0.1 homepageking.de
127.0.0.1 hostedads.realitykings.com
127.0.0.1 hotjar.com
127.0.0.1 hotkeys.com
127.0.0.1 hotlog.ru
127.0.0.1 hotrank.com.tw
127.0.0.1 hs-analytics.net
127.0.0.1 htmlhubing.xyz
127.0.0.1 httpool.com
127.0.0.1 hurricanedigitalmedia.com
127.0.0.1 hydramedia.com
127.0.0.1 hyperbanner.net
127.0.0.1 hypertracker.com
127.0.0.1 i1img.com
127.0.0.1 i1media.no
127.0.0.1 iad.anm.co.uk
127.0.0.1 iadnet.com
127.0.0.1 ia.iinfo.cz
127.0.0.1 iasds01.com
127.0.0.1 i-clicks.net
127.0.0.1 iconadserver.com
127.0.0.1 icptrack.com
127.0.0.1 idcounter.com
127.0.0.1 identads.com
127.0.0.1 idregie.com
127.0.0.1 idtargeting.com
127.0.0.1 ientrymail.com
127.0.0.1 iesnare.com
127.0.0.1 ifa.tube8live.com
127.0.0.1 ilbanner.com
127.0.0.1 ilead.itrack.it
127.0.0.1 illustriousoatmeal.com
127.0.0.1 imageads.canoe.ca
127.0.0.1 imagecash.net
127.0.0.1 images-pw.secureserver.net
127.0.0.1 images.v3.com
127.0.0.1 imarketservices.com
127.0.0.1 img.prohardver.hu
127.0.0.1 imgpromo.easyrencontre.com
127.0.0.1 imonitor.nethost.cz
127.0.0.1 imprese.cz
127.0.0.1 impressionmedia.cz
127.0.0.1 impressionz.co.uk
127.0.0.1 imrworldwide.com
127.0.0.1 inboxdollars.com
127.0.0.1 incentaclick.com
127.0.0.1 incrediblesugar.com
127.0.0.1 indexstats.com
127.0.0.1 indexww.com
127.0.0.1 indieclick.com
127.0.0.1 industrybrains.com
127.0.0.1 inetlog.ru
127.0.0.1 infinite-ads.com
127.0.0.1 infinityads.com
127.0.0.1 infolinks.com
127.0.0.1 information.com
127.0.0.1 inmobi.com
127.0.0.1 innovid.com
127.0.0.1 inringtone.com
127.0.0.1 insightexpressai.com
127.0.0.1 insightexpress.com
127.0.0.1 inspectorclick.com
127.0.0.1 instantmadness.com
127.0.0.1 instinctiveads.com
127.0.0.1 intelliads.com
127.0.0.1 intellitxt.com
127.0.0.1 interactive.forthnet.gr
127.0.0.1 intergi.com
127.0.0.1 internetfuel.com
127.0.0.1 interreklame.de
127.0.0.1 interstat.hu
127.0.0.1 ioam.de
127.0.0.1 ip193.cn
127.0.0.1 iperceptions.com
127.0.0.1 ip.ro
127.0.0.1 ipro.com
127.0.0.1 ireklama.cz
127.0.0.1 itfarm.com
127.0.0.1 itop.cz
127.0.0.1 itsptp.com
127.0.0.1 its-that-easy.com
127.0.0.1 ivwbox.de
127.0.0.1 ivykiosk.com
127.0.0.1 i.xx.openx.com
127.0.0.1 jcount.com
127.0.0.1 jewelcheese.com
127.0.0.1 jinkads.de
127.0.0.1 joetec.net
127.0.0.1 joneself.com
127.0.0.1 jsecoin.com
127.0.0.1 js.users.51.la
127.0.0.1 juicyads.com
127.0.0.1 jumptap.com
127.0.0.1 justrelevant.com
127.0.0.1 justwebads.com
127.0.0.1 kanoodle.com
127.0.0.1 kargo.com
127.0.0.1 karonty.com
127.0.0.1 keymedia.hu
127.0.0.1 k.iinfo.cz
127.0.0.1 kindads.com
127.0.0.1 kissmetrics.com
127.0.0.1 kliks.nl
127.0.0.1 kniverto.com
127.0.0.1 komoona.com
127.0.0.1 kompasads.com
127.0.0.1 kontera.com
127.0.0.1 kt-g.de
127.0.0.1 ktu.sv2.biz
127.0.0.1 lakequincy.com
127.0.0.1 launchbit.com
127.0.0.1 layer-ad.de
127.0.0.1 layer-ads.de
127.0.0.1 lbn.ru
127.0.0.1 lct.salesforce.com
127.0.0.1 lead-analytics.nl
127.0.0.1 leadboltads.net
127.0.0.1 leadclick.com
127.0.0.1 leadingedgecash.com
127.0.0.1 leadzupc.com
127.0.0.1 levelrate.de
127.0.0.1 lfstmedia.com
127.0.0.1 liftdna.com
127.0.0.1 ligatus.com
127.0.0.1 ligatus.de
127.0.0.1 lightningcast.net
127.0.0.1 lightspeedcash.com
127.0.0.1 lijit.com
127.0.0.1 limpingline.com
127.0.0.1 link4ads.com
127.0.0.1 linkadd.de
127.0.0.1 link-booster.de
127.0.0.1 linkbuddies.com
127.0.0.1 linkexchange.com
127.0.0.1 linkprice.com
127.0.0.1 linkrain.com
127.0.0.1 linkreferral.com
127.0.0.1 linkshighway.com
127.0.0.1 links-ranking.de
127.0.0.1 linkstorms.com
127.0.0.1 linkswaper.com
127.0.0.1 linktarget.com
127.0.0.1 liquidad.narrowcastmedia.com
127.0.0.1 liveadexchanger.com
127.0.0.1 liveintent.com
127.0.0.1 liverail.com
127.0.0.1 lizardslaugh.com
127.0.0.1 loading321.com
127.0.0.1 log.btopenworld.com
127.0.0.1 logger.snackly.co
127.0.0.1 logua.com
127.0.0.1 lop.com
127.0.0.1 lopsidedspoon.com
127.0.0.1 loudloss.com
127.0.0.1 lp3tdqle.com
127.0.0.1 lucidmedia.com
127.0.0.1 lumpyleaf.com
127.0.0.1 lzjl.com
127.0.0.1 m1.webstats4u.com
127.0.0.1 m4n.nl
127.0.0.1 mackeeperapp.mackeeper.com
127.0.0.1 madclient.uimserv.net
127.0.0.1 madisonavenue.com
127.0.0.1 mads.cnet.com
127.0.0.1 madvertise.de
127.0.0.1 marchex.com
127.0.0.1 market-buster.com
127.0.0.1 marketing.888.com
127.0.0.1 marketing.hearstmagazines.nl
127.0.0.1 marketing.nyi.net
127.0.0.1 marketing.osijek031.com
127.0.0.1 marketingsolutions.yahoo.com
127.0.0.1 maroonspider.com
127.0.0.1 mas.sector.sk
127.0.0.1 mastermind.com
127.0.0.1 matchcows.com
127.0.0.1 matchcraft.com
127.0.0.1 mathtag.com
127.0.0.1 max.i12.de
127.0.0.1 maximumcash.com
127.0.0.1 mbs.megaroticlive.com
127.0.0.1 mbuyu.nl
127.0.0.1 mdotm.com
127.0.0.1 measuremap.com
127.0.0.1 media6degrees.com
127.0.0.1 media-adrunner.mycomputer.com
127.0.0.1 mediaarea.eu
127.0.0.1 mediabridge.cc
127.0.0.1 mediacharger.com
127.0.0.1 mediadvertising.ro
127.0.0.1 media.ftv-publicite.fr
127.0.0.1 media.funpic.de
127.0.0.1 mediageneral.com
127.0.0.1 mediamath.com
127.0.0.1 mediamgr.ugo.com
127.0.0.1 mediaplazza.com
127.0.0.1 mediaplex.com
127.0.0.1 mediascale.de
127.0.0.1 mediaserver.bwinpartypartners.it
127.0.0.1 media-servers.net
127.0.0.1 mediatext.com
127.0.0.1 mediavoice.com
127.0.0.1 mediax.angloinfo.com
127.0.0.1 mediaz.angloinfo.com
127.0.0.1 medleyads.com
127.0.0.1 medyanetads.com
127.0.0.1 megacash.de
127.0.0.1 megastats.com
127.0.0.1 megawerbung.de
127.0.0.1 metaffiliation.com
127.0.0.1 metanetwork.com
127.0.0.1 methodcash.com
127.0.0.1 metrics.cnn.com
127.0.0.1 metrics.ctv.ca
127.0.0.1 metrics.govexec.com
127.0.0.1 metrics.windowsitpro.com
127.0.0.1 mgid.com
127.0.0.1 miarroba.com
127.0.0.1 microstatic.pl
127.0.0.1 microticker.com
127.0.0.1 midnightclicking.com
127.0.0.1 misstrends.com
127.0.0.1 mixedreading.com
127.0.0.1 mixpanel.com
127.0.0.1 mixtraffic.com
127.0.0.1 mjxads.internet.com
127.0.0.1 ml314.com
127.0.0.1 mlm.de
127.0.0.1 mmismm.com
127.0.0.1 mmtro.com
127.0.0.1 moatads.com
127.0.0.1 mobclix.com
127.0.0.1 mocean.mobi
127.0.0.1 monetate.net
127.0.0.1 moneyexpert.com
127.0.0.1 monsterpops.com
127.0.0.1 mopub.com
127.0.0.1 mouseflow.com
127.0.0.1 mowfruit.com
127.0.0.1 mpstat.us
127.0.0.1 mr-rank.de
127.0.0.1 mrskincash.com
127.0.0.1 mtree.com
127.0.0.1 musiccounter.ru
127.0.0.1 muwmedia.com
127.0.0.1 myaffiliateprogram.com
127.0.0.1 mybloglog.com
127.0.0.1 mycounter.ua
127.0.0.1 mymoneymakingapp.com
127.0.0.1 mypagerank.net
127.0.0.1 mypagerank.ru
127.0.0.1 mypowermall.com
127.0.0.1 mystat-in.net
127.0.0.1 mystat.pl
127.0.0.1 mytop-in.net
127.0.0.1 mytrafficads.com
127.0.0.1 mzbcdn.net
127.0.0.1 n69.com
127.0.0.1 naiadsystems.com.invalid
127.0.0.1 naj.sk
127.0.0.1 namimedia.com
127.0.0.1 nastydollars.com
127.0.0.1 navigator.io
127.0.0.1 navrcholu.cz
127.0.0.1 nbjmp.com
127.0.0.1 ndparking.com
127.0.0.1 nedstatbasic.net
127.0.0.1 nedstat.com
127.0.0.1 nedstat.nl
127.0.0.1 nedstatpro.net
127.0.0.1 nend.net
127.0.0.1 neocounter.neoworx-blog-tools.net
127.0.0.1 neoffic.com
127.0.0.1 nephritish.com
127.0.0.1 netaffiliation.com
127.0.0.1 netagent.cz
127.0.0.1 netclickstats.com
127.0.0.1 netcommunities.com
127.0.0.1 netdirect.nl
127.0.0.1 net-filter.com
127.0.0.1 netincap.com
127.0.0.1 netpool.netbookia.net
127.0.0.1 netshelter.net
127.0.0.1 neudesicmediagroup.com
127.0.0.1 newads.bangbros.com
127.0.0.1 newbie.com
127.0.0.1 newnet.qsrch.com
127.0.0.1 newnudecash.com
127.0.0.1 newopenx.detik.com
127.0.0.1 newt1.adultadworld.com
127.0.0.1 newt1.adultworld.com
127.0.0.1 newtopsites.com
127.0.0.1 nexage.com
127.0.0.1 ng3.ads.warnerbros.com
127.0.0.1 nitroclicks.com
127.0.0.1 novem.pl
127.0.0.1 ntv.io
127.0.0.1 nuggad.net
127.0.0.1 numax.nu-1.com
127.0.0.1 nuseek.com
127.0.0.1 oas.benchmark.fr
127.0.0.1 oascentral.businessweek.com
127.0.0.1 oascentral.chicagobusiness.com
127.0.0.1 oascentral.fortunecity.com
127.0.0.1 oascentral.register.com
127.0.0.1 oas.foxnews.com
127.0.0.1 oas.repubblica.it
127.0.0.1 oas.roanoke.com
127.0.0.1 oas.salon.com
127.0.0.1 oas.toronto.com
127.0.0.1 oas.uniontrib.com
127.0.0.1 oas.villagevoice.com
127.0.0.1 oewa.at
127.0.0.1 oewabox.at
127.0.0.1 offerforge.com
127.0.0.1 offermatica.com
127.0.0.1 olivebrandresponse.com
127.0.0.1 omniture.com
127.0.0.1 onclasrv.com
127.0.0.1 onclickads.net
127.0.0.1 oneandonlynetwork.com
127.0.0.1 onenetworkdirect.com
127.0.0.1 onestat.com
127.0.0.1 onestatfree.com
127.0.0.1 onlinecash.com
127.0.0.1 onlinecashmethod.com
127.0.0.1 online-metrix.net
127.0.0.1 onlinerewardcenter.com
127.0.0.1 openads.friendfinder.com
127.0.0.1 openads.org
127.0.0.1 openad.tf1.fr
127.0.0.1 openad.travelnow.com
127.0.0.1 open.oneplus.net
127.0.0.1 openx.angelsgroup.org.uk
127.0.0.1 openx.blindferret.com
127.0.0.1 opienetwork.com
127.0.0.1 optimost.com
127.0.0.1 optmd.com
127.0.0.1 ordingly.com
127.0.0.1 ota.cartrawler.com
127.0.0.1 otto-images.developershed.com
127.0.0.1 outbrain.com
127.0.0.1 ovalpigs.com
127.0.0.1 overture.com
127.0.0.1 owebmoney.ru
127.0.0.1 owneriq.net
127.0.0.1 oxado.com
127.0.0.1 oxcash.com
127.0.0.1 oxen.hillcountrytexas.com
127.0.0.1 pagead.l.google.com
127.0.0.1 pagefair.com
127.0.0.1 pagerank4you.com
127.0.0.1 pagerank-ranking.de
127.0.0.1 pagerank-submitter.de
127.0.0.1 pageranktop.com
127.0.0.1 pagerank-united.de
127.0.0.1 parsely.com
127.0.0.1 parse.ly.invalid
127.0.0.1 partnerad.l.google.com
127.0.0.1 partner-ads.com
127.0.0.1 partnercash.de
127.0.0.1 partner.pelikan.cz
127.0.0.1 partners.priceline.com
127.0.0.1 partner.topcities.com
127.0.0.1 passion-4.net
127.0.0.1 pay-ads.com
127.0.0.1 paycounter.com
127.0.0.1 paypopup.com
127.0.0.1 payserve.com
127.0.0.1 pbnet.ru
127.0.0.1 pbterra.com
127.0.0.1 pcash.imlive.com
127.0.0.1 peacepowder.com
127.0.0.1 peep-auktion.de
127.0.0.1 peer39.com
127.0.0.1 pennyweb.com
127.0.0.1 pepperjamnetwork.com
127.0.0.1 percentmobile.com
127.0.0.1 perfectaudience.com
127.0.0.1 perfiliate.com
127.0.0.1 performancerevenue.com
127.0.0.1 performancerevenues.com
127.0.0.1 performancing.com
127.0.0.1 pgmediaserve.com
127.0.0.1 pgpartner.com
127.0.0.1 pheedo.com
127.0.0.1 phoenix-adrunner.mycomputer.com
127.0.0.1 photographpan.com
127.0.0.1 phpadsnew.new.natuurpark.nl
127.0.0.1 phpmyvisites.net
127.0.0.1 picadmedia.com
127.0.0.1 piet2eix3l.com
127.0.0.1 pietexture.com
127.0.0.1 pillscash.com
127.0.0.1 pimproll.com
127.0.0.1 pixel.adsafeprotected.com
127.0.0.1 pixel.jumptap.com
127.0.0.1 pixel.redditmedia.com
127.0.0.1 play4traffic.com
127.0.0.1 playhaven.com
127.0.0.1 playmobileads.com
127.0.0.1 plista.com
127.0.0.1 plugrush.com
127.0.0.1 pointroll.com
127.0.0.1 popads.net
127.0.0.1 popflawlessads.com
127.0.0.1 popub.com
127.0.0.1 pop-under.ru
127.0.0.1 popunder.ru
127.0.0.1 popupmoney.com
127.0.0.1 popup.msn.com
127.0.0.1 popupnation.com
127.0.0.1 popups.infostart.com
127.0.0.1 popuptraffic.com
127.0.0.1 porngraph.com
127.0.0.1 porntrack.com
127.0.0.1 possibleboats.com
127.0.0.1 postrelease.com
127.0.0.1 potenza.cz
127.0.0.1 practicetoothpaste.com
127.0.0.1 praddpro.de
127.0.0.1 prchecker.info
127.0.0.1 precisioncounter.com
127.0.0.1 predictad.com
127.0.0.1 premium-offers.com
127.0.0.1 presetrabbits.com
127.0.0.1 primaryads.com
127.0.0.1 primetime.net
127.0.0.1 privatecash.com
127.0.0.1 pro-advertising.com
127.0.0.1 proext.com
127.0.0.1 profero.com
127.0.0.1 profitrumour.com
127.0.0.1 pro.i-doctor.co.kr
127.0.0.1 projectwonderful.com
127.0.0.1 promo1.webcams.nl
127.0.0.1 promo.badoink.com
127.0.0.1 promobenef.com
127.0.0.1 promos.bwin.it
127.0.0.1 promos.fling.com
127.0.0.1 promote.pair.com
127.0.0.1 promotion-campaigns.com
127.0.0.1 promo.ulust.com
127.0.0.1 pronetadvertising.com
127.0.0.1 propellerads.com
127.0.0.1 proranktracker.com
127.0.0.1 proton-tm.com
127.0.0.1 protraffic.com
127.0.0.1 provexia.com
127.0.0.1 provideplant.com
127.0.0.1 prsitecheck.com
127.0.0.1 pr-star.de
127.0.0.1 ps7894.com
127.0.0.1 psstt.com
127.0.0.1 pub.chez.com
127.0.0.1 pub.club-internet.fr
127.0.0.1 pubdirecte.com
127.0.0.1 pub.hardware.fr
127.0.0.1 publicidad.elmundo.es
127.0.0.1 pubmatic.com
127.0.0.1 pub.realmedia.fr
127.0.0.1 pubs.lemonde.fr
127.0.0.1 px.dynamicyield.com
127.0.0.1 q.azcentral.com
127.0.0.1 qctop.com
127.0.0.1 qnsr.com
127.0.0.1 quaintcan.com
127.0.0.1 quantcast.com
127.0.0.1 quantserve.com
127.0.0.1 quarterserver.de
127.0.0.1 questaffiliates.net
127.0.0.1 quicksandear.com
127.0.0.1 quigo.com
127.0.0.1 quinst.com
127.0.0.1 quisma.com
127.0.0.1 radar.cedexis.com
127.0.0.1 radarurl.com
127.0.0.1 radiate.com
127.0.0.1 rad.msn.com
127.0.0.1 rampidads.com
127.0.0.1 rankchamp.de
127.0.0.1 rankingchart.de
127.0.0.1 ranking-charts.de
127.0.0.1 ranking-hits.de
127.0.0.1 ranking-id.de
127.0.0.1 ranking-links.de
127.0.0.1 ranking-liste.de
127.0.0.1 rankingscout.com
127.0.0.1 ranking-street.de
127.0.0.1 rank-master.com
127.0.0.1 rank-master.de
127.0.0.1 rankyou.com
127.0.0.1 rapidcounter.com
127.0.0.1 rate.ru
127.0.0.1 ratings.lycos.com
127.0.0.1 rb1.design.ru
127.0.0.1 reachjunction.com
127.0.0.1 reactx.com
127.0.0.1 readgoldfish.com
127.0.0.1 readserver.net
127.0.0.1 realcastmedia.com
127.0.0.1 realclix.com
127.0.0.1 realmedia-a800.d4p.net
127.0.0.1 realtechnetwork.com
127.0.0.1 realtracker.com
127.0.0.1 receptiveink.com
127.0.0.1 re-directme.com
127.0.0.1 reduxmedia.com
127.0.0.1 reedbusiness.com.invalid
127.0.0.1 referralware.com
127.0.0.1 regnow.com
127.0.0.1 reinvigorate.net
127.0.0.1 reklama.mironet.cz
127.0.0.1 reklama.reflektor.cz
127.0.0.1 reklamcsere.hu
127.0.0.1 reklamer.com.ua
127.0.0.1 reklame.unwired-i.net
127.0.0.1 reklam.rfsl.se
127.0.0.1 relevanz10.de
127.0.0.1 relmaxtop.com
127.0.0.1 remarketingpixel.com
127.0.0.1 remotead.cnet.com
127.0.0.1 remox.com
127.0.0.1 republika.onet.pl
127.0.0.1 retargeter.com
127.0.0.1 revcontent.com
127.0.0.1 revenuedirect.com
127.0.0.1 revenue.net
127.0.0.1 revsci.net
127.0.0.1 revstats.com
127.0.0.1 richmails.com
127.0.0.1 richmedia.yimg.com
127.0.0.1 richwebmaster.com
127.0.0.1 rightstats.com
127.0.0.1 rlcdn.com
127.0.0.1 rle.ru
127.0.0.1 rmads.msn.com
127.0.0.1 rmedia.boston.com
127.0.0.1 roar.com
127.0.0.1 robotreplay.com
127.0.0.1 roia.biz
127.0.0.1 rok.com.com
127.0.0.1 rose.ixbt.com
127.0.0.1 rotabanner.com
127.0.0.1 roxr.net
127.0.0.1 rtbpop.com
127.0.0.1 rtbpopd.com
127.0.0.1 ru4.com
127.0.0.1 rubiconproject.com
127.0.0.1 rulerabbit.com
127.0.0.1 ru-traffic.com
127.0.0.1 s2d6.com
127.0.0.1 s.adroll.com
127.0.0.1 sageanalyst.net
127.0.0.1 sail-horizon.com
127.0.0.1 samsungacr.com
127.0.0.1 samsungads.com
127.0.0.1 saysidewalk.com
127.0.0.1 sbx.pagesjaunes.fr
127.0.0.1 scambiobanner.aruba.it
127.0.0.1 scanscout.com
127.0.0.1 scarcestream.com
127.0.0.1 scopelight.com
127.0.0.1 scorecardresearch.com
127.0.0.1 scratch2cash.com
127.0.0.1 scripte-monster.de
127.0.0.1 scrubsky.com
127.0.0.1 scrubswim.com
127.0.0.1 searchfeast.com
127.0.0.1 searchmarketing.com
127.0.0.1 searchramp.com
127.0.0.1 secure.webconnect.net
127.0.0.1 sedoparking.com
127.0.0.1 sedotracker.com
127.0.0.1 seeq.com.invalid
127.0.0.1 segment.com
127.0.0.1 sensismediasmart.com.au
127.0.0.1 separatesilver.com
127.0.0.1 serv0.com
127.0.0.1 servedbyadbutler.com
127.0.0.1 servedby-buysellads.com
127.0.0.1 servedbyopenx.com
127.0.0.1 servethis.com
127.0.0.1 services.hearstmags.com
127.0.0.1 serving-sys.com
127.0.0.1 sexadvertentiesite.nl
127.0.0.1 sexcounter.com
127.0.0.1 sexinyourcity.com
127.0.0.1 sexlist.com
127.0.0.1 sextracker.com
127.0.0.1 sexystat.com
127.0.0.1 shakesea.com
127.0.0.1 shakytaste.com
127.0.0.1 shareadspace.com
127.0.0.1 shareasale.com
127.0.0.1 sharepointads.com
127.0.0.1 shelterstraw.com
127.0.0.1 sher.index.hu
127.0.0.1 shinystat.com
127.0.0.1 shinystat.it
127.0.0.1 shiveringsail.com
127.0.0.1 shockingswing.com
127.0.0.1 shoppingads.com
127.0.0.1 sidebar.angelfire.com
127.0.0.1 simplisticnose.com
127.0.0.1 sinceresofa.com
127.0.0.1 sinoa.com
127.0.0.1 sitemeter.com
127.0.0.1 sitestat.com
127.0.0.1 sixsigmatraffic.com
127.0.0.1 skimresources.com
127.0.0.1 skylink.vn
127.0.0.1 slickaffiliate.com
127.0.0.1 slopeaota.com
127.0.0.1 smart4ads.com
127.0.0.1 smartadserver.com
127.0.0.1 smart.brvaffs.com
127.0.0.1 smartlook.com
127.0.0.1 smetrics.walgreens.com
127.0.0.1 smowtion.com
127.0.0.1 snakesort.com
127.0.0.1 snapads.com
127.0.0.1 sneaklevel.com
127.0.0.1 sneakystamp.com
127.0.0.1 snoobi.com
127.0.0.1 socialspark.com
127.0.0.1 softclick.com.br
127.0.0.1 sonobi.com
127.0.0.1 spacash.com
127.0.0.1 sparkstudios.com
127.0.0.1 specially4u.net
127.0.0.1 specificmedia.co.uk
127.0.0.1 specificpop.com
127.0.0.1 spectacularsnail.com
127.0.0.1 spezialreporte.de
127.0.0.1 spillvacation.com
127.0.0.1 spinbox.techtracker.com
127.0.0.1 spinbox.versiontracker.com
127.0.0.1 sponsorads.de
127.0.0.1 sponsorpro.de
127.0.0.1 sponsors.thoughtsmedia.com
127.0.0.1 spot.fitness.com
127.0.0.1 spotxchange.com
127.0.0.1 spykemediatrack.co
127.0.0.1 spykemediatrack.com
127.0.0.1 spylog.com
127.0.0.1 spywarelabs.com
127.0.0.1 spywarenuker.com
127.0.0.1 spywords.com
127.0.0.1 squeamishscarecrow.com
127.0.0.1 srwww1.com
127.0.0.1 starffa.com
127.0.0.1 start.freeze.com
127.0.0.1 stat24.com
127.0.0.1 stat24.meta.ua
127.0.0.1 stat.cliche.se
127.0.0.1 statcounter.com
127.0.0.1 stat.dealtime.com
127.0.0.1 stat.dyna.ultraweb.hu
127.0.0.1 staticads.btopenworld.com
127.0.0.1 static.fmpub.net
127.0.0.1 static.itrack.it
127.0.0.1 statistik-gallup.net
127.0.0.1 statm.the-adult-company.com
127.0.0.1 stat.pl
127.0.0.1 stats2.self.com
127.0.0.1 stats4all.com
127.0.0.1 stats.blogger.com
127.0.0.1 stats.directnic.com
127.0.0.1 stats.hyperinzerce.cz
127.0.0.1 statsie.com
127.0.0.1 stats.merriam-webster.com
127.0.0.1 stats.mirrorfootball.co.uk
127.0.0.1 stats.multiup.org
127.0.0.1 stats.olark.com
127.0.0.1 stats.pusher.com
127.0.0.1 stats.self.com
127.0.0.1 stats.townnews.com
127.0.0.1 stats.unwired-i.net
127.0.0.1 stats.wordpress.com
127.0.0.1 stats.x14.eu
127.0.0.1 stat.webmedia.pl
127.0.0.1 statxpress.com
127.0.0.1 stat.zenon.net
127.0.0.1 steelhouse.com
127.0.0.1 steelhousemedia.com
127.0.0.1 stickyadstv.com
127.0.0.1 storesurprise.com
127.0.0.1 stormyachiever.com
127.0.0.1 stormyshock.com
127.0.0.1 stormysponge.com
127.0.0.1 straightnest.com
127.0.0.1 strivesidewalk.com
127.0.0.1 structuresofa.com
127.0.0.1 suavalds.com
127.0.0.1 subscribe.hearstmags.com
127.0.0.1 succeedscene.com
127.0.0.1 sugoicounter.com
127.0.0.1 sumo.com
127.0.0.1 sumome.com
127.0.0.1 superclix.de
127.0.0.1 superficialsink.com
127.0.0.1 superstats.com
127.0.0.1 supertop100.com
127.0.0.1 supertop.ru
127.0.0.1 surfmusik-adserver.de
127.0.0.1 swan-swan-goose.com
127.0.0.1 swissadsolutions.com
127.0.0.1 swordfishdc.com
127.0.0.1 sx.trhnt.com
127.0.0.1 taboola.com
127.0.0.1 tacoda.net
127.0.0.1 tagular.com
127.0.0.1 tailsweep.com
127.0.0.1 tailsweep.co.uk
127.0.0.1 tailsweep.se
127.0.0.1 takru.com
127.0.0.1 tangerinenet.biz
127.0.0.1 tapad.com
127.0.0.1 targad.de
127.0.0.1 targetingnow.com
127.0.0.1 targetnet.com
127.0.0.1 targetpoint.com
127.0.0.1 tatsumi-sys.jp
127.0.0.1 tcads.net
127.0.0.1 teads.tv
127.0.0.1 techclicks.net
127.0.0.1 teenrevenue.com
127.0.0.1 teliad.de
127.0.0.1 terribleturkey.com
127.0.0.1 test.invalid
127.0.0.1 textads.biz
127.0.0.1 textad.sexsearch.com
127.0.0.1 text-link-ads.com
127.0.0.1 textlinks.com
127.0.0.1 tfag.de
127.0.0.1 theadhost.com
127.0.0.1 theads.me
127.0.0.1 thebugs.ws
127.0.0.1 thecounter.com
127.0.0.1 thecounter.com.invalid
127.0.0.1 therapistla.com
127.0.0.1 therichkids.com
127.0.0.1 thirdrespect.com
127.0.0.1 thrnt.com
127.0.0.1 throattrees.com
127.0.0.1 thruport.com
127.0.0.1 tidytrail.com
127.0.0.1 t.insigit.com
127.0.0.1 tinybar.com
127.0.0.1 tizers.net
127.0.0.1 tlvmedia.com
127.0.0.1 tns-counter.ru
127.0.0.1 tntclix.co.uk
127.0.0.1 top100-images.rambler.ru
127.0.0.1 top100.mafia.ru
127.0.0.1 top123.ro
127.0.0.1 top20.com.invalid
127.0.0.1 top20free.com
127.0.0.1 top90.ro
127.0.0.1 topbarh.box.sk
127.0.0.1 topbucks.com
127.0.0.1 top-casting-termine.de
127.0.0.1 topforall.com
127.0.0.1 topgamesites.net
127.0.0.1 toplista.mw.hu
127.0.0.1 toplistcity.com
127.0.0.1 toplist.cz
127.0.0.1 toplist.pornhost.com
127.0.0.1 top.list.ru
127.0.0.1 top.mail.ru
127.0.0.1 topmmorpgsites.com.invalid
127.0.0.1 topping.com.ua
127.0.0.1 top.proext.com
127.0.0.1 toprebates.com
127.0.0.1 topsafelist.net
127.0.0.1 topsearcher.com
127.0.0.1 topsir.com
127.0.0.1 top-site-list.com
127.0.0.1 topsite.lv
127.0.0.1 topsites.com.br
127.0.0.1 topstats.com
127.0.0.1 totemcash.com
127.0.0.1 touchclarity.com
127.0.0.1 touchclarity.natwest.com
127.0.0.1 tour.brazzers.com
127.0.0.1 tpnads.com
127.0.0.1 t.pusk.ru
127.0.0.1 tracedesire.com
127.0.0.1 track.adform.net
127.0.0.1 trackalyzer.com
127.0.0.1 track.anchorfree.com
127.0.0.1 tracker.icerocket.com
127.0.0.1 tracker.marinsm.com
127.0.0.1 track.flexlinks.com
127.0.0.1 track.flexlinkspro.com
127.0.0.1 track.gawker.com
127.0.0.1 tracking101.com
127.0.0.1 tracking.crunchiemedia.com
127.0.0.1 tracking.gajmp.com
127.0.0.1 tracking.internetstores.de
127.0.0.1 trackingsoft.com
127.0.0.1 trackmysales.com
127.0.0.1 tradeadexchange.com
127.0.0.1 tradedoubler.com
127.0.0.1 trafficadept.com
127.0.0.1 trafficbalancerouting.com
127.0.0.1 traffic-exchange.com
127.0.0.1 trafficfactory.biz
127.0.0.1 traffic.focuusing.com
127.0.0.1 trafficholder.com
127.0.0.1 traffichunt.com
127.0.0.1 trafficjunky.net
127.0.0.1 trafficleader.com
127.0.0.1 trafficsecrets.com
127.0.0.1 trafficspaces.net
127.0.0.1 trafficstrategies.com
127.0.0.1 trafficswarm.com
127.0.0.1 traffictrader.net
127.0.0.1 trafficz.com
127.0.0.1 trafficz.net
127.0.0.1 traffiq.com
127.0.0.1 trafic.ro
127.0.0.1 travis.bosscasinos.com
127.0.0.1 trekblue.com
127.0.0.1 trekdata.com
127.0.0.1 trendcounter.com
127.0.0.1 trendmd.com
127.0.0.1 trhunt.com
127.0.0.1 tribalfusion.com
127.0.0.1 trickycelery.com
127.0.0.1 tritetongue.com
127.0.0.1 trix.net
127.0.0.1 trmit.com
127.0.0.1 truehits1.gits.net.th
127.0.0.1 truehits2.gits.net.th
127.0.0.1 truehits.net
127.0.0.1 tsyndicate.com
127.0.0.1 tubemogul.com
127.0.0.1 turn.com
127.0.0.1 tvmtracker.com
127.0.0.1 twittad.com
127.0.0.1 tyroo.com
127.0.0.1 uarating.com
127.0.0.1 ukbanners.com
127.0.0.1 ultimateclixx.com
127.0.0.1 ultramercial.com
127.0.0.1 unknowntray.com
127.0.0.1 untd.com
127.0.0.1 unusualtitle.com
127.0.0.1 updated.com
127.0.0.1 urlcash.net
127.0.0.1 us.a1.yimg.com
127.0.0.1 usapromotravel.com
127.0.0.1 userreplay.com
127.0.0.1 userreplay.net
127.0.0.1 utarget.co.uk
127.0.0.1 utils.mediageneral.net
127.0.0.1 v1.cnzz.com
127.0.0.1 validclick.com
127.0.0.1 valuead.com
127.0.0.1 valueclick.com
127.0.0.1 valueclickmedia.com
127.0.0.1 valuecommerce.com
127.0.0.1 valuesponsor.com
127.0.0.1 veille-referencement.com
127.0.0.1 ventivmedia.com
127.0.0.1 vericlick.com
127.0.0.1 vertadnet.com
127.0.0.1 veruta.com
127.0.0.1 vervewireless.com
127.0.0.1 vibrantmedia.com
127.0.0.1 videoegg.com
127.0.0.1 video-stats.video.google.com
127.0.0.1 view4cash.de
127.0.0.1 viewpoint.com
127.0.0.1 visistat.com
127.0.0.1 visitbox.de
127.0.0.1 visit.webhosting.yahoo.com
127.0.0.1 visual-pagerank.fr
127.0.0.1 visualrevenue.com
127.0.0.1 voicefive.com
127.0.0.1 voicevegetable.com
127.0.0.1 vpon.com
127.0.0.1 vrs.cz
127.0.0.1 vs.tucows.com
127.0.0.1 vungle.com
127.0.0.1 warlog.ru
127.0.0.1 wdads.sx.atl.publicus.com
127.0.0.1 web2.deja.com
127.0.0.1 webads.co.nz
127.0.0.1 webads.nl
127.0.0.1 webangel.ru
127.0.0.1 webcash.nl
127.0.0.1 webcounter.cz
127.0.0.1 webcounter.goweb.de
127.0.0.1 webgains.com
127.0.0.1 web.informer.com
127.0.0.1 webmaster-partnerprogramme24.de
127.0.0.1 webmasterplan.com
127.0.0.1 webmasterplan.de
127.0.0.1 weborama.fr
127.0.0.1 webpower.com
127.0.0.1 webreseau.com
127.0.0.1 webseoanalytics.com
127.0.0.1 websponsors.com
127.0.0.1 webstat.channel4.com
127.0.0.1 web-stat.com
127.0.0.1 webstat.com
127.0.0.1 webstat.net
127.0.0.1 webstats4u.com
127.0.0.1 webtrackerplus.com
127.0.0.1 webtraffic.se
127.0.0.1 webtraxx.de
127.0.0.1 webtrendslive.com
127.0.0.1 werbung.meteoxpress.com
127.0.0.1 wetrack.it
127.0.0.1 whaleads.com
127.0.0.1 whenu.com
127.0.0.1 whispa.com
127.0.0.1 whoisonline.net
127.0.0.1 wholesaletraffic.info
127.0.0.1 widespace.com
127.0.0.1 widgetbucks.com
127.0.0.1 wikia-ads.wikia.com
127.0.0.1 window.nixnet.cz
127.0.0.1 wintricksbanner.googlepages.com
127.0.0.1 witch-counter.de
127.0.0.1 wlmarketing.com
127.0.0.1 wmirk.ru
127.0.0.1 wonderlandads.com
127.0.0.1 wondoads.de
127.0.0.1 woopra.com
127.0.0.1 worldwide-cash.net
127.0.0.1 ws-gateway.com
127.0.0.1 wtlive.com
127.0.0.1 www1.gto-media.com
127.0.0.1 www8.glam.com
127.0.0.1 www-banner.chat.ru
127.0.0.1 www.banner-link.com.br
127.0.0.1 www.dnps.com
127.0.0.1 www-google-analytics.l.google.com
127.0.0.1 www.kaplanindex.com
127.0.0.1 www.money4exit.de
127.0.0.1 www.photo-ads.co.uk
127.0.0.1 wwwpromoter.com
127.0.0.1 x6.yakiuchi.com
127.0.0.1 xchange.ro
127.0.0.1 xclicks.net
127.0.0.1 xertive.com
127.0.0.1 xg4ken.com
127.0.0.1 xiti.com
127.0.0.1 xplusone.com
127.0.0.1 xponsor.com
127.0.0.1 xq1.net
127.0.0.1 xrea.com
127.0.0.1 xtendmedia.com
127.0.0.1 x-traceur.com
127.0.0.1 xtremetop100.com
127.0.0.1 xxxcounter.com
127.0.0.1 xxxmyself.com
127.0.0.1 yab-adimages.s3.amazonaws.com
127.0.0.1 yabuka.com
127.0.0.1 yadro.ru
127.0.0.1 yesads.com
127.0.0.1 yesadvertising.com
127.0.0.1 y.ibsys.com
127.0.0.1 yieldads.com
127.0.0.1 yieldlab.net
127.0.0.1 yieldmanager.com
127.0.0.1 yieldmanager.net
127.0.0.1 yieldmo.com
127.0.0.1 yieldtraffic.com
127.0.0.1 yldbt.com
127.0.0.1 yoggrt.com
127.0.0.1 z5x.net
127.0.0.1 zangocash.com
127.0.0.1 zanox-affiliate.de
127.0.0.1 zanox.com
127.0.0.1 zantracker.com
127.0.0.1 zedo.com
127.0.0.1 zencudo.co.uk
127.0.0.1 zenkreka.com
127.0.0.1 zenzuu.com
127.0.0.1 zeusclicks.com
127.0.0.1 zeus.developershed.com
127.0.0.1 zintext.com
127.0.0.1 zmedia.com
127.0.0.1 zv1.november-lax.com
180hits.de
180searchassistant.com
207.net
247media.com
24log.com
24log.de
24pm-affiliation.com
2mdn.net
2o7.net
360yield.com
4affiliate.net
4d5.net
50websads.com
518ad.com
51yes.com
600z.com
777partner.com
77tracking.com
7bpeople.com
7search.com
99count.com
a.0day.kiev.ua
a32.g.a.yimg.com
aaddzz.com
a-ads.com
a.aproductmsg.com
abacho.net
abandonedclover.com
abc-ads.com
abruptroad.com
absoluteclickscom.com
abz.com
accounts.pkr.com.invalid
a.collective-media.net
a.consumer.net
a-counter.kiev.ua
ac.rnm.ca
acsseo.com
actionsplash.com
actualdeals.com
actuallysheep.com
acuityads.com
acuty1adsrv.com
ad01.mediacorpsingapore.com
ad0.bigmir.net
ad.100.tbn.ru
ad1.emediate.dk
ad1.emule-project.org
ad1.kde.cz
ad1.pamedia.com.au
ad2flash.com
ad2games.com
ad2.iinfo.cz
ad2.linxcz.cz
ad2.lupa.cz
ad3.iinfo.cz
ad3.pamedia.com.au
ad4game.com
ad.71i.de
ad.a8.net
ad.abcnews.com
ad.abctv.com
ad.aboutwebservices.com
ad.abum.com
adaction.de
ad.admitad.com
adadvisor.net
ad.afy11.net
ad.allstar.cz
ad.altervista.org
ad.amgdgt.com
ad.anuntis.com
adapt.tv
adap.tv
ad.auditude.com
ad-balancer.at
ad-balancer.net
adbanner.ro
adbard.net
adbers.com
ad.bizo.com
adblade.com
adblockanalytics.com
ad.bnmla.com
ad.bondage.com
adboost.de.vu
adboost.net
adbooth.net
adbot.com
adbrite.com
adbroker.de
adbunker.com
adbutler.com
adbutler.de
adbuyer3.lycos.com
adbuyer.com
ad.caradisiac.com
adcash.com
adcast.deviantart.com
adcell.de
ad-center.com
adcenter.mdf.se
adcenter.net
adcentriconline.com
ad.centrum.cz
adcept.net
ad.cgi.cz
ad.choiceradio.com
adclick.com
adclient1.tucows.com
adclient.uimserv.net
ad.clix.pt
adcomplete.com
adconion.com
adcontent.gamespy.com
ad.cooks.com
ad.crwdcntrl.net
adcycle.com
addealing.com
addfreestats.com
ad.digitallook.com
ad.directrev.com
addme.com
add.newmedia.cz
ad.doctissimo.fr
ad.domainfactory.de
adecn.com
ad.e-kolay.net
ademails.com
adengage.com
ad.eurosport.com
adexchangegate.com
adexchangeprediction.com
adexcite.com
adexpose.com
adext.inkclub.com
ad.f1cd.ru
adfactor.nl
adfactor.nl.invalid
adfarm.mediaplex.com
adflight.com
ad.flurry.com
adf.ly
adforce.com
adform.com
ad.foxnetworks.com
ad.freecity.de
adgardener.com
ad.gate24.ch
ad.globe7.com
adgoto.com
ad.grafika.cz
adgridwork.com
ad.hbv.de
adhese.be
adhese.com
ad.hodomobile.com
ad.httpool.com
ad.hyena.cz
ad.iinfo.cz
ad.ilove.ch
adimage.asiaone.com.sg
adimage.guardian.co.uk
adimages.been.com
adimages.carsoup.com
adimages.go.com
adimages.homestore.com
adimages.omroepzeeland.nl
adimages.sanomawsoy.fi
adimg1.chosun.com
adimg.cnet.com
adimg.com.com
adimgs.sapo.pt
adimg.uimserv.net
adimpact.com
adincube.com
ad.infoseek.com
adinjector.net
adinterax.com
adisfy.com
adition.com
adition.de
adition.net
adizio.com
ad.jamba.net
ad.jamster.co.uk
ad.jetsoftware.com
adjix.com
adjug.com
adjuggler.com
adjuggler.yourdictionary.com
adjustnetwork.com
adk2ads.tictacti.com
adk2.com
ad.keenspace.com
adland.ru
adlantic.nl
ad.leadbolt.net
adledge.com
adlegend.com
ad.liveinternet.ru
adlog.com.com
adloox.com
adlooxtracking.com
ad.lupa.cz
adlure.net
admagnet.net
admailtiser.com
admanagement.ch
admanager.btopenworld.com
admanager.carsoup.com
adman.gr
adman.in.gr
adman.otenet.gr
admarketplace.net
admarvel.com
admax.nexage.com
admedia.com
admedia.ro
ad.media-servers.net
ad.mediastorm.hu
admeld.com
admerize.be
admeta.com
admex.com
ad.mgd.de
adminder.com
adminshop.com
admized.com
admob.com
admonitor.com
admotion.com.ar
ad.musicmatch.com
ad.nachtagenten.de
adnet.asahi.com
adnet.biz
adnet.de
adnetinteractive.com
adnet-media.net
adnet.ru
adnetwork.net
adnetworkperformance.com
adnet.worldreviewer.com
adnews.maddog2000.de
adnotch.com
ad.nozonedata.com
ad.nttnavi.co.jp
ad.nwt.cz
adnxs.com
adocean.pl
ad.onad.eu
adonspot.com
adoperator.com
adorigin.com
ad.pandora.tv
ad-pay.de
adpepper.dk
adpepper.nl
adperium.com
adpia.vn
adplus.co.id
adplxmd.com
ad.preferances.com
adprofile.net
ad.profiwin.de
adprojekt.pl
ad.prv.pl
adq.nextag.com
ad.rambler.ru
adrazzi.com
adreactor.com
adreclaim.com
adrecreate.com
adremedy.com
adreporting.com
adres.internet.com
ad.reunion.com
adrevolver.com
adriver.ru
adrolays.de
adrotate.de
ad-rotator.com
adrotator.se
adrta.com
ads03.redtube.com
ads10.speedbit.com
ads180.com
ads1.canoe.ca
ads1.mediacapital.pt
ads1.msn.com
ads1.rne.com
ads1.virtual-nights.com
ads2004.treiberupdate.de
ads2.brazzers.com
ads2.clearchannel.com
ads2.contentabc.com
ads2.gamecity.net
ads2.jubii.dk
ads2.net-communities.co.uk
ads2.oneplace.com
ads2.rne.com
ads2.virtual-nights.com
ads2.xnet.cz
ads3.contentabc.com
ads3.gamecity.net
ads3.virtual-nights.com
ads4.clearchannel.com
ads4.gamecity.net
ads4homes.com
ads.4tube.com
ads4.virtual-nights.com
ads5.canoe.ca
ads.5ci.lt
ads5.virtual-nights.com
ads6.gamecity.net
ads7.gamecity.net
ads8.com
ads.abovetopsecret.com
ads.aceweb.net
ads.activestate.com
ads.adfox.ru
ads.administrator.de
ads.adshareware.net
ads.adultfriendfinder.com
ads.adultswim.com
ads.advance.net
ads.adverline.com
adsafeprotected.com
ads.affiliates.match.com
ads.ak.facebook.com.edgesuite.net
ads.allvatar.com
ads.alt.com
ads.amdmb.com
ads.amigos.com
ads.aol.com
ads.aol.co.uk
ads.apn.co.nz
ads.appsgeyser.com
ads.as4x.tmcs.net
ads.as4x.tmcs.ticketmaster.com
ads.asia1.com.sg
ads.asiafriendfinder.com
ads.ask.com
ads.aspalliance.com
Adsatt.ABCNews.starwave.com
adsatt.abc.starwave.com
adsatt.espn.go.com
adsatt.espn.starwave.com
Adsatt.go.starwave.com
ads.avazu.net
ads.batpmturner.com
ads.beenetworks.net
ads.belointeractive.com
ads.berlinonline.de
ads.betanews.com
ads.betfair.com
ads.betfair.com.au
ads.bigchurch.com
ads.bigfoot.com
ads.bing.com
ads.bittorrent.com
ads.blog.com
ads.bloomberg.com
ads.bluelithium.com
ads.bluemountain.com
ads.bluesq.com
ads.bonniercorp.com
ads.boylesports.com
ads.brabys.com
ads.brazzers.com
ads.bumq.com
ads.businessweek.com
adsby.bidtheatre.com
adscale.de
ads.canalblog.com
ad.scanmedios.com
ads.canoe.ca
ads.casinocity.com
ads.cbc.ca
ads.cc
ads.cc-dt.com
ads.centraliprom.com
ads.cgnetworks.com
ads.channel4.com
adscholar.com
adscience.nl
ads.clearchannel.com
ads-click.com
ads.co.com
ads.com.com
ads.contactmusic.com
ads.contentabc.com
ads.contextweb.com
adscpm.com
ads.crakmedia.com
ads.creativematch.com
ads.creative-serving.com
ads.cricbuzz.com
ads.cybersales.cz
ads.dada.it
adsdaq.com
ads.datinggold.com
ads.datingyes.com
ads.dazoot.ro
ads.deltha.hu
ads.dennisnet.co.uk
ads.desmoinesregister.com
ads.detelefoongids.nl
ads.deviantart.com
ads.digital-digest.com
ads.digitalmedianet.com
ads.digitalpoint.com
ads.directionsmag.com
adsdk.com
ads.domain.com
ads.domeus.com
ads.eagletribune.com
ads.easy-forex.com
ads.eatinparis.com
ads.economist.com
ads.edbindex.dk
ads.egrana.com.br
ads.einmedia.com
ads.electrocelt.com
ads.elitetrader.com
ads.emirates.net.ae
adsend.de
ad.sensismediasmart.com.au
ads.epltalk.com
adserve.ams.rhythmxchange.com
adserver01.de
adserver1.backbeatmedia.com
adserver1-images.backbeatmedia.com
adserver1.mindshare.de
adserver1.ogilvy-interactive.de
adserver2.mindshare.de
adserver.43plc.com
adserver.71i.de
adserver.adultfriendfinder.com
adserver.aidameter.com
adserver.aol.fr
adserver.beggarspromo.com
adserver.betandwin.de
adserver.bing.com
adserver.bizhat.com
adserver.break-even.it
adserver.cams.com
adserver.com
adserver.digitoday.com
adserver.dotcommedia.de
adserver.finditquick.com
adserver.flossiemediagroup.com
adserver.freecity.de
adserver.freenet.de
adserver.friendfinder.com
ad-server.gulasidorna.se
adserver.hardsextube.com
adserver.hardwareanalysis.com
adserver.html.it
adserver.irishwebmasterforum.com
adserver.janes.com
adserver.libero.it
# Ad server list for use with hosts files to block ads
adserver-live.yoc.mobi
adserver.news.com.au
adserver.ngz-network.de
adserver.nydailynews.com
adserver.o2.pl
adserver.oddschecker.com
adserver.omroepzeeland.nl
ad-serverparc.nl
adserver.pl
adserverplus.com
adserver.portalofevil.com
adserver.portugalmail.net
adserver.portugalmail.pt
adserver.sanomawsoy.fi
adserver.sciflicks.com
adserver.sharewareonline.com
adserversolutions.com
adserver.spankaway.com
adserver.startnow.com
adserver.theonering.net
adserver.twitpic.com
adserver.viagogo.com
adserver.virginmedia.com
adserver.yahoo.com
adserv.evo-x.de
adserv.gamezone.de
adserv.iafrica.com
adservinginternational.com
adserv.qconline.com
ads.eu.msn.com
ads.exactdrive.com
ads.expat-blog.biz
ads.expedia.com
ads.ezboard.com
ad.seznam.cz
adsfac.eu
adsfac.net
ads.factorymedia.com
adsfac.us
ads.fairfax.com.au
ads.faxo.com
ads.ferianc.com
ads.filmup.com
ads.financialcontent.com
ads.flooble.com
ads.fool.com
ads.footymad.net
ads.forbes.com
ads.forbes.net
ads.forium.de
ads.fortunecity.com
ads.fotosidan.se
ads.foxkidseurope.net
ads.foxnetworks.com
ads.foxnews.com
ads.freecity.de
ads.friendfinder.com
ads.ft.com
ads.futurenet.com
ads.gamecity.net
ads.gamershell.com
ads.gamespyid.com
ads.gamigo.de
ads.gaming-universe.de
ads.gawker.com
ads.geekswithblogs.net
ads.glispa.com
ads.gmodules.com
ads.godlikeproductions.com
ads.goyk.com
ads.gplusmedia.com
ads.gradfinder.com
ads.grindinggears.com
ads.groundspeak.com
ads.gsm-exchange.com
ads.gsmexchange.com
ads.guardian.co.uk
ads.guardianunlimited.co.uk
ads.guru3d.com
ads.hardwaresecrets.com
ads.harpers.org
ads.hbv.de
ads.hearstmags.com
ads.heartlight.org
ads.heias.com
ads.hideyourarms.com
ads.hollywood.com
ads.horsehero.com
ads.horyzon-media.com
adshost1.com
ads.iafrica.com
ads.ibest.com.br
ads.ibryte.com
ads.icq.com
adside.com
ads.ign.com
ad.simgames.net
ads.img.co.za
ads.imgur.com
ads.indiatimes.com
ads.infi.net
ads.internic.co.il
ads.ipowerweb.com
ads.isoftmarketing.com
ads.itv.com
ads.iwon.com
ads.jewishfriendfinder.com
ads.jiwire.com
ads.jobsite.co.uk
ads.jpost.com
ads.jubii.dk
ads.justhungry.com
adsk2.co
ads.kaktuz.net
adskape.ru
ads.kelbymediagroup.com
ads.kinobox.cz
ads.kinxxx.com
adsklick.de
ads.kompass.com
ads.krawall.de
ads.lesbianpersonals.com
ads.linkedin.com
ads.linuxfoundation.org
ads.linuxjournal.com
ads.linuxsecurity.com
ads.livenation.com
ad.slutload.com
ads.mariuana.it
adsmarket.com
ad.smartclip.net
adsmart.com
adsmart.co.uk
adsmart.net
ads.massinfra.nl
ads.mcafee.com
ads.mediaodyssey.com
ads.medienhaus.de
ads.mgnetwork.com
ads.mmania.com
ads.moceanads.com
adsmogo.com
ads.motor-forum.nl
ads.motormedia.nl
ads.msn.com
ads.multimania.lycos.fr
ads.nationalgeographic.com
adsnative.com
ads.ncm.com
ads.netclusive.de
ads.netmechanic.com
ads.networksolutions.com
ads.newdream.net
ads.newgrounds.com
ads.newmedia.cz
ads.newsint.co.uk
ads.newsquest.co.uk
ads.ninemsn.com.au
ads.nj.com
ads.nola.com
ads.nordichardware.com
ads.nordichardware.se
ads.nwsource.com
ads.nyi.net
ads.nytimes.com
ads.nyx.cz
ads.nzcity.co.nz
ads.o2.pl
ads.oddschecker.com
adsoftware.com
ads.okcimg.com
adsoldier.com
ads.ole.com
ads.olivebrandresponse.com
adsonar.com
ads.oneplace.com
ads.ookla.com
ads.optusnet.com.au
ad-souk.com
ads.outpersonals.com
ad-space.net
adspace.ro
ads.passion.com
adspeed.net
ads.pennet.com
ads.penny-arcade.com
ads.pheedo.com
ads.phpclasses.org
ads.pickmeup-ltd.com
adspirit.de
ads.planet.nl
ads.pni.com
ads.pof.com
adsponse.de
ads.powweb.com
ads.primissima.it
ads.printscr.com
ads.prisacom.com
ads.program3.com
ads.psd2html.com
ads.pushplay.com
ads.quoka.de
ads.rcs.it
ads.recoletos.es
ads.rediff.com
ads.redlightcenter.com
ads.redtube.com
adsremote.scrippsnetworks.com
ads.resoom.de
ads.returnpath.net
adsrevenue.net
adsrv.deviantart.com
adsrv.eacdn.com
adsrv.iol.co.za
adsrvr.org
ads.s3.sitepoint.com
ads.satyamonline.com
ads.savannahnow.com
ads.saymedia.com
ads.scifi.com
ads.seniorfriendfinder.com
ads.servebom.com
ads.sexinyourcity.com
ads.shizmoo.com
ads.shopstyle.com
ads.sift.co.uk
ads.silverdisc.co.uk
ads.slim.com
ads.smartclick.com
ads.soft32.com
ads.space.com
ads.sptimes.com
ads.stackoverflow.com
adsstat.com
ads.sun.com
ads.supplyframe.com
ads.tahono.com
adstat.4u.pl
ads.techtv.com
ads.telegraph.co.uk
adstest.weather.com
ads.themovienation.com
ads.thestar.com
ads.tmcs.net
ads.t-online.de
ads.totallyfreestuff.com
ads.townhall.com
ads.trinitymirror.co.uk
ads.tripod.com
ads.tripod.lycos.co.uk
ads.tripod.lycos.de
ads.tripod.lycos.es
ads.tripod.lycos.it
ads.tripod.lycos.nl
ads.tripod.spray.se
ads.tso.dennisnet.co.uk
ads.uknetguide.co.uk
ads.ultimate-guitar.com
ads.uncrate.com
ads.undertone.com
adsupply.com
ads.usatoday.com
ads.v3.com
ads.verticalresponse.com
ads.vgchartz.com
ads.videosz.com
ads.virtualcountries.com
ads.virtual-nights.com
ads.vnumedia.com
ads.waps.cn
ads.wapx.cn
ads.weather.ca
ads.web.aol.com
ads.web.cs.com
ads.web.de
ads.webmasterpoint.org
ads.websiteservices.com
ads.whi.co.nz
ads.whoishostingthis.com
ads.wiezoekje.nl
ads.wikia.nocookie.net
ads.wineenthusiast.com
adswizz.com
ads.wwe.biz
ads.xhamster.com
ads.xtra.co.nz
ads.y-0.net
ads.yahoo.com
ads.yimg.com
ads.yldmgrimg.net
adsymptotic.com
adsynergy.com
ads.yourfreedvds.com
ads.youtube.com
adsystem.simplemachines.org
adsys.townnews.com
ads.zdnet.com
ads.ztod.com
ad.tbn.ru
ad-tech.com
adtech.de
ad.technoratimedia.com
adtechus.com
adtegrity.net
ad.thewheelof.com
adthis.com
adtiger.de
adtoll.com
adtology.com
adtoma.com
adtrace.org
adtrade.net
adtrading.de
adtrak.net
adtriplex.com
ad.turn.com
ad.tv2.no
ad.twitchguru.com
adultadvertising.com
ad-up.com
ad.usatoday.com
adv-adserver.com
advariant.com
adv-banner.libero.it
adv.cooperhosting.net
adventory.com
advert.bayarea.com
advert.dyna.ultraweb.hu
adverticum.com
adverticum.net
adverticus.de
advertise.com
advertiseireland.com
advertiserurl.com
advertisespace.com
advertisingbanners.com
advertisingbox.com
advertising.com
advertising.guildlaunch.net
advertisingtag.net
advertmarket.com
advertmedia.de
advertpro.sitepoint.com
advertpro.ya.com
adverts.carltononline.com
advertserve.com
advertstream.com
advertwizard.com
adv.freeonline.it
adv.hwupgrade.it
advideo.uimserv.net
adview.ppro.de
ad.virtual-nights.com
advisormedia.cz
adviva.net
adv.livedoor.com
advnt.com
adv.webmd.com
adv.wp.pl
adv.yo.cz
adwareremovergold.com
ad.wavu.hu
ad.way.cz
ad.weatherbug.com
adwhirl.com
adwitserver.com
adworldnetwork.com
adworx.at
adworx.be
adworx.nl
ad.wsod.com
ad.wz.cz
adx.allstar.cz
adx.atnext.com
adxpansion.com
adxpose.com
adxprts.com
adxvalue.com
ad.yadro.ru
adyea.com
ad.yourmedia.com
adz2you.com
ad.zanox.com
adzbazar.com
adzerk.net
adzerk.s3.amazonaws.com
adzones.com
af-ad.co.uk
affbuzzads.com
affiliate.1800flowers.com
affiliate.doubleyourdating.com
affiliate.dtiserv.com
affiliatefuel.com
affiliatefuture.com
affiliate.gamestop.com
affiliate.mercola.com
affiliate.mogs.com
affiliate.offgamers.com
affiliates.allposters.com
affiliates.babylon.com
affiliates.digitalriver.com
affiliates.globat.com
affiliates.internationaljock.com
affiliates.streamray.com
affiliates.thinkhost.net
affiliates.thrixxx.com
affiliates.ultrahosting.com
affiliatetracking.com
affiliatetracking.net
affiliate.travelnow.com
affiliate.viator.com
affiliatewindow.com
affiliation-france.com
affili.net
afftracking.justanswer.com
ahalogy.com
ah-ha.com
aidu-ads.de
aim4media.com
aistat.net
aktrack.pubmatic.com
alclick.com
alenty.com
alexa-sitestats.s3.amazonaws.com
alipromo.com
all4spy.com
alladvantage.com
allosponsor.com
amazingcounters.com
amazon-adsystem.com
ambitiousagreement.com
americash.com
a.mktw.net
amung.us
anahtars.com
analytics.adpost.org
analytics.google.com
analytics.live.com
analytics.yahoo.com
anm.intelli-direct.com
annonser.dagbladet.no
an.tacoda.net
anxiousapples.com
apex-ad.com
api.intensifier.de
app.adblockhyper.us
appsflyer.com
apture.com
arc1.msn.com
arcadebanners.com
ard.xxxblackbook.com
are-ter.com
as1.advfn.com
a.sakh.com
assets1.exgfnetwork.com
assoc-amazon.com
as.webmd.com
at-adserver.alltop.com
atdmt.com
athena-ads.wikia.com
atwola.com
a.ucoz.net
a.ucoz.ru
auctionads.com
auctionads.net
audience2media.com
audit.median.hu
audit.webinform.hu
auto-bannertausch.de
autohits.dk
avenuea.com
avpa.javalobby.org
avres.net
avsads.com
avzadsrv.com
awempire.com
awin1.com
a.xanga.com
azfront.com
b0b1o.bid
b-1st.com
ba.afl.rakuten.co.jp
babs.tv2.dk
backbeatmedia.com
banik.redigy.cz
banner.ad.nu
bannerads.de
banner.ambercoastcasino.com
banner.blogranking.net
bannerboxes.com
banner.buempliz-online.ch
banner.casinodelrio.com
banner.casino.net
bannercommunity.de
bannerconnect.com
bannerconnect.net
banner.cotedazurpalace.com
banner.coza.com
banner.cz
banner.easyspace.com
banner.elisa.net
banner.eurogrand.com
banner-exchange-24.de
bannerexchange.cjb.net
banner.featuredusers.com
bannerflow.com
banner.getgo.de
banner.goldenpalace.com
bannergrabber.internet.gr
bannerhost.com
bannerimage.com
banner.img.co.za
banner.inyourpocket.com
banner.kiev.ua
bannerlandia.com.ar
banner.linux.se
bannermall.com
bannermarkt.nl
banner.media-system.de
banner.mindshare.de
banner.nixnet.cz
banner.noblepoker.com
banner.northsky.com
banner.orb.net
banner.penguin.cz
bannerpower.com
banner.rbc.ru
banner.relcom.ru
banners.adultfriendfinder.com
banners.amigos.com
banners.asiafriendfinder.com
banners.audioholics.com
banners.babylon-x.com
banners.bol.com.br
banners.cams.com
banners.clubseventeen.com
banners.czi.cz
banners.dine.com
banners.direction-x.com
banners.directnic.com
banners.easydns.com
bannerserver.com
banners.freett.com
banners.friendfinder.com
banners.getiton.com
bannersgomlm.com
bannershotlink.perfectgonzo.com
banners.iq.pl
banners.isoftmarketing.com
banners.lifeserv.com
banners.linkbuddies.com
bannersng.yell.com
bannerspace.com
banners.passion.com
banners.resultonline.com
banners.sexsearch.com
banners.sys-con.com
banners.thomsonlocal.com
banners.videosz.com
banners.virtuagirlhd.com
bannerswap.com
banners.wunderground.com
banner.tanto.de
bannertesting.com
banner.titan-dsl.de
banner.vadian.net
banner.webmersion.com
banner.wirenode.com
bannery.cz
bannieres.acces-contenu.com
bans.adserver.co.il
bans.bride.ru
b.aol.com
barnesandnoble.bfast.com
basebanner.com
baskettexture.com
bawdybeast.com
baypops.com
bbelements.com
bbn.img.com.ua
beamincrease.com
beamkite.com
begun.ru
belstat.com
belstat.nl
b.engadget.com
berp.com
best-pr.info
bestsearch.net
best-top.ro
bhclicks.com
bidclix.com
bidclix.net
bidswitch.net
bidtrk.com
bidvertiser.com
bigbangmedia.com
bigclicks.com
billboard.cz
bitads.net
bitmedianetwork.com
bizad.nikkeibp.co.jp
bizographics.com
bizrate.com
blast4traffic.com
blingbucks.com
blogads.com
blogcounter.de
blogherads.com
blogrush.com
blogtoplist.se
blogtopsites.com
blueadvertise.com
bluekai.com
bluelithium.com
bluewhaleweb.com
bm.annonce.cz
bn.bfast.com
boersego-ads.de
boilingbeetle.com
boldchat.com
boomads.com
boom.ro
boost-my-pr.de
box.anchorfree.net
bpath.com
braincash.com
brandreachsys.com
brassrule.com
bravenet.com.invalid
bridgetrack.com
brightinfo.com
british-banners.com
broadboundary.com
bs.yandex.ru
bttrack.com
budsinc.com
bullseye.backbeatmedia.com
buyhitscheap.com
buysellads.com
buzzonclick.com
bvalphaserver.com
bwp.download.com
c1exchange.com
c1.nowlinux.com
calmfoot.com
campaign.bharatmatrimony.com
caniamedia.com
carambo.la
carbonads.com
carbonads.net
casalemedia.com
casalmedia.com
cash4members.com
cash4popup.de
cashcrate.com
cashengines.com
cashfiesta.com
cashlayer.com
cashpartner.com
casinogames.com
casinopays.com
casinorewards.com
casinotraffic.com
casinotreasure.com
cbanners.virtuagirlhd.com
c.bigmir.net
cbmall.com
cdn.freefacti.com
cdn.freefarcy.com
cecash.com
centerpointmedia.com
ceskydomov.alias.ngs.modry.cz
cetrk.com
cgicounter.puretec.de
chameleon.ad
channelintelligence.com
chartbeat.com
chartbeat.net
chart.dk
checkm8.com
checkstat.nl
cherrythread.com
chestionar.ro
chiefcurrent.com
chinchickens.com
chitika.net
ch.questionmarket.com
cibleclick.com
cibleclick.com.invalid
cityads.telus.net
cjbmanagement.com
cj.com
cjlog.com
claria.com
class-act-clicks.com
click2freemoney.com
click2paid.com
clickability.com
click.absoluteagency.com
clickadz.com
clickagents.com
clickbank.com
clickbank.net
clickbooth.com
clickboothlnk.com
clickbrokers.com
clickcompare.co.uk
clickdensity.com
clickedyclick.com
click.fool.com
clickhereforcellphones.com
clickhouse.com
clickhype.com
click.kmindex.ru
clicklink.jp
clickmedia.ro
clickonometrics.pl
clicks.equantum.com
clickserve.cc-dt.com
clicks.mods.de
clicksor.com
clicktag.de
clickthrucash.com
clickthruserver.com
clickthrutraffic.com
clicktrace.info
clicktracks.com
clicktrack.ziyu.net
clicktrade.com
clickxchange.com
clickz.com
clickzxc.com
clicmanager.fr
clientmetrics-pa.googleapis.com
clients.tbo.com
clikerz.net
cliksolution.com
cliqz.com
clixgalore.com
clkads.com
clk.konflab.com
clkrev.com
cluster.adultworld.com
clustrmaps.com
cmpstar.com
cnomy.com
cnt1.pocitadlo.cz
cnt.spbland.ru
code-server.biz
coinhive.com
colonize.com
comclick.com
commandwalk.com
commindo-media-ressourcen.de
commissionmonster.com
compactbanner.com
comprabanner.it
concernrain.com
confirmed-profits.com
connextra.com
consciouscabbage.com
contaxe.de
content.acc-hd.de
content.ad
contextweb.com
conversantmedia.com
conversionruler.com
cookies.cmpnet.com
copperchickens.com
copycarpenter.com
copyrightaccesscontrols.com
coremetrics.com
counted.com
counter.bloke.com
counter.cnw.cz
counter.cz
counter.dreamhost.com
counter.fateback.com
counter.mirohost.net
counter.mojgorod.ru
counter.nowlinux.com
counter.rambler.ru
counter.search.bg
counters.honesty.com
counter.snackly.co
counter.sparklit.com
counter.yadro.ru
counting.kmindex.ru
count.rbc.ru
count.rin.ru
counts.tucows.com
count.west263.com
coupling-media.de
cpalead.com
cpays.com
cpmaffiliation.com
cpmstar.com
cpxinteractive.com
cqcounter.com
crakmedia.com
craktraffic.com
crawlability.com
crawlclocks.com
crazypopups.com
creafi-online-media.com
creatives.as4x.tmcs.net
creatives.livejasmin.com
creative.whi.co.nz
# credits:        Peter Lowe - pgl@yoyo.org - https://pgl.yoyo.org/ - https://twitter.com/pgl
crispads.com
criteo.com
critictruck.com
crowdgravity.com
crownclam.com
crtv.mate1.com
crwdcntrl.net
ctnetwork.hu
cubics.com
curtaincows.com
customad.cnn.com
cutecushion.com
cyberbounty.com
cybermonitor.com
d.adroll.com
dakic-ia-300.com
danban.com
dapper.net
datashreddergold.com
dbbsrv.com
dc-storm.com
de17a.com
dealdotcom.com
debtbusterloans.com
decisiveducks.com
decknetwork.net
delightdriving.com
deloo.de
deloton.com
demandbase.com
demdex.net
di1.shopping.com
dialerporn.com
dianomi.com
didtheyreadit.com
differentdesk.com
digital-ads.s3.amazonaws.com
digitalmerkat.com
directaclick.com
directivepub.com
directleads.com
directorym.com
directtrack.com
direct-xxx-access.com
discountclick.com
displayadsmedia.com
dist.belnk.com
dk4ywix.com
dmtracker.com
dmtracking2.alibaba.com
dmtracking.alibaba.com
dnads.directnic.com
docksalmon.com
domaining.in
domainsponsor.com
domainsteam.de
domdex.com
doubleclick.com
doubleclick.de
doubleclick.net
doublepimp.com
doubtfulrainstorm.com
dragzebra.com
drumcash.com
dynamic.fmpub.net
dynamicyield.com
eadexchange.com
e-adimages.scrippsnetworks.com
eas.almamedia.fi
easyhits4u.com
e-bannerx.com
ebayadvertising.com
ebocornac.com
ebuzzing.com
ecircle-ag.com
eclick.vn
ecoupons.com
e-debtconsolidation.com
edgeio.com
effectivemeasure.com
effectivemeasure.net
eiv.baidu.com
e.kde.cz
elasticchange.com
elephantqueue.com
elitedollars.com
elitetoplist.com
emarketer.com
emediate.dk
emediate.eu
e-m.fr
engine.espace.netavenir.com
enginenetwork.com
enoratraffic.com
enquisite.com
entercasino.com
e-n-t-e-r-n-e-x.com
entrecard.s3.amazonaws.com
# entries:        2456
# entries:        2466
# entries:        2467
# entries:        2469
# entries:        2470
# entries:        2472
# entries:        2477
# entries:        2479
# entries:        2480
# entries:        2484
e-planning.net
eqads.com
ero-advertising.com
esellerate.net
estat.com
etahub.com
etargetnet.com
etracker.de
eu1.madsone.com
eu-adcenter.net
eur.a1.yimg.com
eurekster.com
euroclick.com
euro-linkindex.de
euros4click.de
eusta.de
evergage.com
evidencecleanergold.com
ewebcounter.com
exchangead.com
exchange.bg
exchangeclicksonline.com
exchange-it.com
exclusivebrass.com
exelator.com
exit76.com
exitexchange.com
exitfuel.com
exoclick.com
exogripper.com
experteerads.com
exponential.com
express-submit.de
extractorandburner.com
extreme-dm.com
extremetracking.com
eyeblaster.com
eyeota.net
eyereturn.com
eyeviewads.com
eyewonder.com
ezula.com
f5biz.com
fast-adv.it
fastclick.com
fastclick.com.edgesuite.net
fastclick.net
fb-promotions.com
fc.webmasterpro.de
feedbackresearch.com
feedjit.com
ffxcam.fairfax.com.au
fimc.net
fimserve.com
findcommerce.com
findyourcasino.com
fineclicks.com
firstlightera.com
first.nova.cz
flashtalking.com
flavordecision.com
fleshlightcash.com
flexbanner.com
floodprincipal.com
flowgo.com
flurry.com
fonecta.leiki.com
foo.cosmocode.de
forex-affiliate.net
# format:         hosts (hosts -- in hosts file format)
# For more information about this list, see: https://pgl.yoyo.org/adservers/
fpctraffic2.com
fpctraffic.com
fqtag.com
fragmentserv.iac-online.de
freebanner.com
free-banners.com
freelogs.com
freeonlineusers.com
freepay.com
freestats.com
freestats.tv
freewebcounter.com
functionalclam.com
funklicks.com
funpageexchange.com
fusionads.net
fusionquest.com
futuristicfairies.com
fuzzyflavor.com
fxstyle.net
ga87z2o.com
galaxien.com
game-advertising-online.com
gamehouse.com
gamesites100.net
gamesites200.com
gamesitestop100.com
gator.com
gbanners.hornymatches.com
gemius.pl
geobanner.adultfriendfinder.com
geo.digitalpoint.com
geovisite.com
getclicky.com
giddycoat.com
gigya.com.invalid
globalismedia.com
globaltakeoff.net
globaltrack.com.invalid
globe7.com
globus-inter.com
gmads.net
go-clicks.de
goingplatinum.com
goldstats.com
googleadservices.com
google-analytics.com
googlesyndication.com
go-rank.de
gorgeousground.com
gostats.com
gp.dejanews.com
gpr.hu
grafstat.ro
grapeshot.co.uk
greetzebra.com
greystripe.com
gtop100.com
gtop.ro
guardedgovernor.com
guitarbelieve.com
gunggo.com
harrenmedia.com
harrenmedianetwork.com
havamedia.net
heias.com
hellobar.com
hentaicounter.com
herbalaffiliateprogram.com
hexusads.fluent.ltd.uk
heyos.com
hgads.com
hidden.gogoceleb.com
hightrafficads.com
hilariouszinc.com
histats.com
hit.bg
hitbox.com
hitcents.com
hitfarm.com
hitiz.com
hitlist.ru
hitlounge.com
hitometer.com
hit-parade.com
hits4me.com
hits4pay.com
hits.europuls.eu
hits.informer.com
hitslink.com
hits.puls.lv
hits.theguardian.com
hittail.com
hit.ua
hit.webcentre.lycos.co.uk
hollandbusinessadvertising.nl
homepageking.de
hostedads.realitykings.com
hotjar.com
hotkeys.com
hotlog.ru
hotrank.com.tw
hs-analytics.net
htmlhubing.xyz
httpool.com
hurricanedigitalmedia.com
hydramedia.com
hyperbanner.net
hypertracker.com
i1img.com
i1media.no
iad.anm.co.uk
iadnet.com
ia.iinfo.cz
iasds01.com
i-clicks.net
iconadserver.com
icptrack.com
idcounter.com
identads.com
idot.cz
idregie.com
idtargeting.com
ientrymail.com
iesnare.com
ifa.tube8live.com
ilbanner.com
ilead.itrack.it
illustriousoatmeal.com
ilovecheating.com
imageads.canoe.ca
imagecash.net
images-pw.secureserver.net
images.v3.com
imarketservices.com
img.prohardver.hu
imgpromo.easyrencontre.com
imonitor.nethost.cz
imprese.cz
impressionmedia.cz
impressionz.co.uk
imrworldwide.com
inboxdollars.com
incentaclick.com
incrediblesugar.com
indexstats.com
indieclick.com
industrybrains.com
inetlog.ru
infinite-ads.com
infinityads.com
infolinks.com
information.com
inmobi.com
inringtone.com
insightexpressai.com
insightexpress.com
inspectorclick.com
instantmadness.com
intelliads.com
intellitxt.com
interactive.forthnet.gr
intergi.com
internetfuel.com
interreklame.de
interstat.hu
ip193.cn
iperceptions.com
ip.ro
ipro.com
ireklama.cz
itfarm.com
itop.cz
itsptp.com
its-that-easy.com
ivykiosk.com
i.xx.openx.com
jcount.com
jewelcheese.com
jinkads.de
joetec.net
js.users.51.la
juicyads.com
jumptap.com
justrelevant.com
justwebads.com
kanoodle.com
keymedia.hu
k.iinfo.cz
kindads.com
kissmetrics.com
kliks.nl
kniverto.com
komoona.com
kompasads.com
kontera.com
kt-g.de
ktu.sv2.biz
lakequincy.com
# last updated:   Fri, 10 Nov 2017 15:17:09 GMT
# last updated:   Fri, 24 Nov 2017 11:53:05 GMT
# last updated:   Mon, 06 Nov 2017 09:32:14 GMT
# last updated:   Sat, 18 Nov 2017 20:57:32 GMT
# last updated:   Sat, 25 Nov 2017 12:55:16 GMT
# last updated:   Sun, 19 Nov 2017 19:57:33 GMT
# last updated:   Thu, 12 Oct 2017 15:12:09 GMT
# last updated:   Tue, 14 Nov 2017 16:06:41 GMT
# last updated:   Tue, 17 Oct 2017 10:03:39 GMT
# last updated:   Wed, 08 Nov 2017 09:34:12 GMT
# last updated:   Wed, 15 Nov 2017 11:10:17 GMT
# last updated:   Wed, 25 Oct 2017 06:55:31 GMT
# last updated:   Wed, 25 Oct 2017 07:55:31 GMT
launchbit.com
layer-ad.de
layer-ads.de
lbn.ru
lct.salesforce.com
lead-analytics.nl
leadboltads.net
leadclick.com
leadingedgecash.com
leadzupc.com
levelrate.de
lfstmedia.com
liftdna.com
ligatus.com
ligatus.de
lightningcast.net
lightspeedcash.com
limpingline.com
link4ads.com
linkadd.de
link-booster.de
linkbuddies.com
linkexchange.com
linkprice.com
linkrain.com
linkreferral.com
linkshighway.com
links-ranking.de
linkstorms.com
linkswaper.com
linktarget.com
liquidad.narrowcastmedia.com
liveadexchanger.com
liveintent.com
liverail.com
lizardslaugh.com
loading321.com
log.btopenworld.com
logger.snackly.co
logua.com
lop.com
lopsidedspoon.com
loudloss.com
lp3tdqle.com
lucidmedia.com
lumpyleaf.com
lzjl.com
m1.webstats4u.com
m4n.nl
mackeeperapp.mackeeper.com
madclient.uimserv.net
madisonavenue.com
mads.cnet.com
madvertise.de
marchex.com
market-buster.com
marketing.888.com
marketing.hearstmagazines.nl
marketing.nyi.net
marketing.osijek031.com
marketingsolutions.yahoo.com
maroonspider.com
mas.sector.sk
mastermind.com
matchcows.com
matchcraft.com
mathtag.com
max.i12.de
maximumcash.com
mbn.com.ua
mbs.megaroticlive.com
mbuyu.nl
mdotm.com
measuremap.com
media6degrees.com
media-adrunner.mycomputer.com
mediaarea.eu
mediabridge.cc
mediacharger.com
mediadvertising.ro
media.ftv-publicite.fr
media.funpic.de
mediageneral.com
mediamath.com
mediamgr.ugo.com
mediaplazza.com
mediaplex.com
mediascale.de
media-servers.net
mediatext.com
mediax.angloinfo.com
mediaz.angloinfo.com
medleyads.com
medyanetads.com
megacash.de
megago.com
megastats.com
megawerbung.de
metaffiliation.com
metanetwork.com
methodcash.com
metrics.cnn.com
metrics.ctv.ca
metrics.windowsitpro.com
mgid.com
miarroba.com
microstatic.pl
microticker.com
midnightclicking.com
misstrends.com
mixedreading.com
mixpanel.com
mixtraffic.com
mjxads.internet.com
mlm.de
mmismm.com
mmtro.com
moatads.com
mobclix.com
mocean.mobi
moneyexpert.com
monsterpops.com
mopub.com
mouseflow.com
mowfruit.com
mpstat.us
mr-rank.de
mrskincash.com
mtree.com
musiccounter.ru
muwmedia.com
m.webtrends.com
myaffiliateprogram.com
mybloglog.com
mycounter.ua
mymoneymakingapp.com
mypagerank.net
mypagerank.ru
mypowermall.com
mystat-in.net
mystat.pl
mytop-in.net
mytrafficads.com
n69.com
naiadsystems.com.invalid
naj.sk
namimedia.com
nastydollars.com
navigator.io
navrcholu.cz
nbjmp.com
ndparking.com
nedstatbasic.net
nedstat.com
nedstat.nl
nedstatpro.net
nend.net
neocounter.neoworx-blog-tools.net
neoffic.com
netaffiliation.com
netagent.cz
netclickstats.com
netcommunities.com
netdirect.nl
net-filter.com
netincap.com
netpool.netbookia.net
netshelter.net
neudesicmediagroup.com
newads.bangbros.com
newbie.com
newnet.qsrch.com
newnudecash.com
newopenx.detik.com
newt1.adultadworld.com
newt1.adultworld.com
newtopsites.com
nexage.com
ng3.ads.warnerbros.com
ngs.impress.co.jp
nitroclicks.com
novem.pl
nuggad.net
numax.nu-1.com
nuseek.com
oas.benchmark.fr
oascentral.businessweek.com
oascentral.chicagobusiness.com
oascentral.fortunecity.com
oascentral.register.com
oas.foxnews.com
oas.repubblica.it
oas.roanoke.com
oas.salon.com
oas.toronto.com
oas.uniontrib.com
oas.villagevoice.com
oewa.at
oewabox.at
offerforge.com
offermatica.com
olivebrandresponse.com
omniture.com
onclasrv.com
onclickads.net
oneandonlynetwork.com
onenetworkdirect.com
onestat.com
onestatfree.com
onlinecash.com
onlinecashmethod.com
online-metrix.net
onlinerewardcenter.com
openads.friendfinder.com
openads.org
openad.tf1.fr
openad.travelnow.com
open.oneplus.net
openx.angelsgroup.org.uk
openx.blindferret.com
opienetwork.com
optimost.com
optmd.com
ordingly.com
ota.cartrawler.com
# other formats:  https://pgl.yoyo.org/adservers/formats.php
otto-images.developershed.com
outbrain.com
ovalpigs.com
overture.com
owebmoney.ru
oxado.com
oxcash.com
oxen.hillcountrytexas.com
p.adpdx.com
pagead.l.google.com
pagefair.com
pagerank4you.com
pagerank-ranking.de
pagerank-submitter.de
pageranktop.com
pagerank-united.de
parsely.com
parse.ly.invalid
partage-facile.com
partnerad.l.google.com
partner-ads.com
partnercash.de
partner.pelikan.cz
partners.priceline.com
partner.topcities.com
passion-4.net
pay-ads.com
paycounter.com
paypopup.com
payserve.com
pbnet.ru
pbterra.com
pcash.imlive.com
peacepowder.com
peep-auktion.de
peer39.com
pennyweb.com
pepperjamnetwork.com
percentmobile.com
perfectaudience.com
perfiliate.com
performancerevenue.com
performancerevenues.com
performancing.com
pgmediaserve.com
pgpartner.com
pheedo.com
phoenix-adrunner.mycomputer.com
photographpan.com
phpadsnew.new.natuurpark.nl
phpmyvisites.net
picadmedia.com
pietexture.com
pillscash.com
pimproll.com
pixel.adsafeprotected.com
pixel.jumptap.com
pixel.redditmedia.com
play4traffic.com
playhaven.com
playmobileads.com
plista.com
plugrush.com
pointroll.com
# policy:         https://pgl.yoyo.org/adservers/policy.php
popads.net
popflawlessads.com
popub.com
pop-under.ru
popunder.ru
popupmoney.com
popup.msn.com
popupnation.com
popups.infostart.com
popuptraffic.com
porngraph.com
porntrack.com
possibleboats.com
postrelease.com
potenza.cz
practicetoothpaste.com
praddpro.de
prchecker.info
precisioncounter.com
predictad.com
premium-offers.com
presetrabbits.com
primaryads.com
primetime.net
privatecash.com
pro-advertising.com
proext.com
profero.com
profitrumour.com
pro.i-doctor.co.kr
projectwonderful.com
promo1.webcams.nl
promo.badoink.com
promobenef.com
promos.fling.com
promote.pair.com
promotion-campaigns.com
promo.ulust.com
pronetadvertising.com
propellerads.com
proranktracker.com
proton-tm.com
protraffic.com
provexia.com
provideplant.com
prsitecheck.com
pr-star.de
pr-ten.de
psstt.com
pub.chez.com
pub.club-internet.fr
pubdirecte.com
pub.hardware.fr
publicidad.elmundo.es
pubmatic.com
pub.realmedia.fr
pubs.lemonde.fr
pulse360.com
px.dynamicyield.com
q.azcentral.com
qctop.com
qnsr.com
quaintcan.com
quantcast.com
quantserve.com
quarterserver.de
questaffiliates.net
quicksandear.com
quigo.com
quinst.com
quisma.com
radar.cedexis.com
radarurl.com
radiate.com
rad.msn.com
rampidads.com
rankchamp.de
rankingchart.de
ranking-charts.de
ranking-hits.de
ranking-id.de
ranking-links.de
ranking-liste.de
rankingscout.com
ranking-street.de
rank-master.com
rank-master.de
rankyou.com
rapidcounter.com
rate.ru
ratings.lycos.com
rb1.design.ru
reachjunction.com
reactx.com
readgoldfish.com
readserver.net
realcastmedia.com
realclix.com
realmedia-a800.d4p.net
realtechnetwork.com
realtracker.com
receptiveink.com
re-directme.com
reduxmedia.com
reduxmediagroup.com
reedbusiness.com.invalid
referralware.com
regnow.com
reinvigorate.net
reklama.mironet.cz
reklama.reflektor.cz
reklamcsere.hu
reklamer.com.ua
reklame.unwired-i.net
reklam.rfsl.se
relevanz10.de
relmaxtop.com
remarketingpixel.com
remotead.cnet.com
remox.com
republika.onet.pl
retargeter.com
revcontent.com
revenuedirect.com
revenue.net
revsci.net
revstats.com
richmails.com
richmedia.yimg.com
richwebmaster.com
rightstats.com
rlcdn.com
rle.ru
rmads.msn.com
rmedia.boston.com
roar.com
robotreplay.com
roia.biz
rok.com.com
rose.ixbt.com
rotabanner.com
roxr.net
rtbpop.com
rtbpopd.com
ru4.com
rubiconproject.com
rulerabbit.com
ru-traffic.com
s2d6.com
s.adroll.com
sageanalyst.net
sail-horizon.com
samsungacr.com
samsungads.com
saysidewalk.com
sbx.pagesjaunes.fr
scambiobanner.aruba.it
scanscout.com
scarcestream.com
scopelight.com
scorecardresearch.com
scratch2cash.com
scripte-monster.de
scrubsky.com
scrubswim.com
searchfeast.com
searchmarketing.com
searchramp.com
secure.webconnect.net
sedoparking.com
sedotracker.com
seeq.com.invalid
segment.com
sensismediasmart.com.au
seo4india.com
separatesilver.com
serv0.com
servedbyadbutler.com
servedby-buysellads.com
servedbyopenx.com
servethis.com
services.hearstmags.com
serving-sys.com
sexaddpro.de
sexadvertentiesite.nl
sexcounter.com
sexinyourcity.com
sexlist.com
sextracker.com
sexystat.com
shakesea.com
shakytaste.com
shareadspace.com
shareasale.com
sharepointads.com
shelterstraw.com
sher.index.hu
shinystat.com
shinystat.it
shiveringsail.com
shockingswing.com
shoppingads.com
siccash.com
sidebar.angelfire.com
simplisticnose.com
sinceresofa.com
sinoa.com
sitemeter.com
sitestat.com
sixsigmatraffic.com
skimresources.com
skylink.vn
slickaffiliate.com
slopeaota.com
smart4ads.com
smartadserver.com
smowtion.com
snakesort.com
snapads.com
sneaklevel.com
sneakystamp.com
snoobi.com
socialspark.com
softclick.com.br
sonobi.com
spacash.com
sparkstudios.com
specially4u.net
specificmedia.co.uk
specificpop.com
spectacularsnail.com
spezialreporte.de
spillvacation.com
spinbox.techtracker.com
spinbox.versiontracker.com
sponsorads.de
sponsorpro.de
sponsors.thoughtsmedia.com
spot.fitness.com
spotxchange.com
spykemediatrack.co
spykemediatrack.com
spylog.com
spywarelabs.com
spywarenuker.com
spywords.com
squeamishscarecrow.com
srwww1.com
starffa.com
# start date:    Fri, 07 Nov 1997 00:00:00
# start date:    Fri, 21 Nov 1997 00:00:00
# start date:    Fri, 24 Oct 1997 00:00:00
# start date:    Fri, 28 Nov 1997 00:00:00
# start date:    Fri, 31 Oct 1997 00:00:00
# start date:    Mon, 01 Dec 1997 00:00:00
# start date:    Mon, 03 Nov 1997 00:00:00
# start date:    Mon, 10 Nov 1997 00:00:00
# start date:    Mon, 17 Nov 1997 00:00:00
# start date:    Mon, 20 Oct 1997 00:00:00
# start date:    Mon, 24 Nov 1997 00:00:00
# start date:    Mon, 27 Oct 1997 00:00:00
# start date:    Sat, 01 Nov 1997 00:00:00
# start date:    Sat, 08 Nov 1997 00:00:00
# start date:    Sat, 25 Oct 1997 00:00:00
# start date:    Sat, 29 Nov 1997 00:00:00
# start date:    Sun, 02 Nov 1997 00:00:00
# start date:    Sun, 16 Nov 1997 00:00:00
# start date:    Sun, 26 Oct 1997 00:00:00
# start date:    Sun, 30 Nov 1997 00:00:00
# start date:    Thu, 13 Nov 1997 00:00:00
# start date:    Thu, 20 Nov 1997 00:00:00
# start date:    Thu, 23 Oct 1997 00:00:00
# start date:    Thu, 27 Nov 1997 00:00:00
# start date:    Thu, 30 Oct 1997 00:00:00
# start date:    Tue, 04 Nov 1997 00:00:00
# start date:    Tue, 11 Nov 1997 00:00:00
# start date:    Tue, 18 Nov 1997 00:00:00
# start date:    Tue, 25 Nov 1997 00:00:00
# start date:    Tue, 28 Oct 1997 00:00:00
# start date:    Wed, 05 Nov 1997 00:00:00
# start date:    Wed, 19 Nov 1997 00:00:00
# start date:    Wed, 29 Oct 1997 00:00:00
start.freeze.com
stat24.com
stat24.meta.ua
stat.cliche.se
statcounter.com
stat.dealtime.com
stat.dyna.ultraweb.hu
staticads.btopenworld.com
static.fmpub.net
static.itrack.it
statistik-gallup.net
statm.the-adult-company.com
stat.pl
stats2.self.com
stats4all.com
stats.blogger.com
stats.cts-bv.nl
stats.directnic.com
stats.hyperinzerce.cz
statsie.com
stats.merriam-webster.com
stats.mirrorfootball.co.uk
stats.multiup.org
stats.olark.com
stats.pusher.com
stats.self.com
stats.suite101.com
stats.surfaid.ihost.com
stats.townnews.com
stat.su
stats.unwired-i.net
stats.wordpress.com
stats.x14.eu
stat.webmedia.pl
statxpress.com
stat.zenon.net
steelhouse.com
steelhousemedia.com
stickyadstv.com
storesurprise.com
stormyachiever.com
stormyshock.com
stormysponge.com
straightnest.com
strivesidewalk.com
structuresofa.com
suavalds.com
subscribe.hearstmags.com
succeedscene.com
sugoicounter.com
sumo.com
sumome.com
superclix.de
superficialsink.com
superstats.com
supertop100.com
supertop.ru
suptullog.com
surfmusik-adserver.de
swan-swan-goose.com
swissadsolutions.com
swordfishdc.com
sx.trhnt.com
taboola.com
tacoda.net
tagular.com
tailsweep.com
tailsweep.co.uk
tailsweep.se
takru.com
tangerinenet.biz
tapad.com
targad.de
targetingnow.com
targetnet.com
targetpoint.com
tatsumi-sys.jp
tcads.net
teads.tv
techclicks.net
teenrevenue.com
teliad.de
terribleturkey.com
test.invalid
textads.biz
textad.sexsearch.com
textads.opera.com
text-link-ads.com
textlinks.com
tfag.de
theadhost.com
theads.me
thebugs.ws
thecounter.com
therapistla.com
therichkids.com
thirdrespect.com
# this URL:       http://pgl.yoyo.org/as/serverlist.php?mimetype=plaintext
thrnt.com
throattrees.com
thruport.com
tidytrail.com
t.insigit.com
tinybar.com
tizers.net
tlvmedia.com
tntclix.co.uk
top100-images.rambler.ru
top100.mafia.ru
top123.ro
top20.com.invalid
top20free.com
top90.ro
topbarh.box.sk
topblogarea.se
topbucks.com
top-casting-termine.de
topforall.com
topgamesites.net
toplista.mw.hu
toplistcity.com
toplist.cz
toplist.pornhost.com
top.list.ru
top.mail.ru
topmmorpgsites.com.invalid
topping.com.ua
top.proext.com
toprebates.com
topsafelist.net
topsearcher.com
topsir.com
top-site-list.com
topsite.lv
topsites.com.br
topstats.com
totemcash.com
touchclarity.com
touchclarity.natwest.com
tour.brazzers.com
tpnads.com
t.pusk.ru
tracedesire.com
track.adform.net
trackalyzer.com
track.anchorfree.com
tracker.icerocket.com
tracker.marinsm.com
track.flexlinks.com
track.flexlinkspro.com
track.gawker.com
tracking101.com
tracking.crunchiemedia.com
tracking.gajmp.com
tracking.internetstores.de
trackingsoft.com
tracking.yourfilehost.com
trackmysales.com
tradeadexchange.com
tradedoubler.com
trafficadept.com
trafficbalancerouting.com
trafficcdn.liveuniversenetwork.com
traffic-exchange.com
trafficfactory.biz
traffic.focuusing.com
trafficholder.com
traffichunt.com
trafficjunky.net
trafficleader.com
traffic.liveuniversenetwork.com
trafficsecrets.com
trafficspaces.net
trafficstrategies.com
trafficswarm.com
traffictrader.net
trafficz.com
trafficz.net
traffiq.com
trafic.ro
travis.bosscasinos.com
trekblue.com
trekdata.com
trendcounter.com
trendmd.com
trhunt.com
tribalfusion.com
trickycelery.com
tritetongue.com
trix.net
trmit.com
truehits1.gits.net.th
truehits2.gits.net.th
truehits.net
tsms-ad.tsms.com
tubemogul.com
turn.com
tvmtracker.com
twittad.com
tyroo.com
uarating.com
ukbanners.com
ultimateclixx.com
ultramercial.com
unanimis.co.uk
unknowntray.com
untd.com
unusualtitle.com
updated.com
urlcash.net
us.a1.yimg.com
usapromotravel.com
usmsad.tom.com
utarget.co.uk
utils.mediageneral.net
v1.cnzz.com
validclick.com
valuead.com
valueclick.com
valueclickmedia.com
valuecommerce.com
valuesponsor.com
veille-referencement.com
ventivmedia.com
vericlick.com
vertadnet.com
veruta.com
vervewireless.com
vibrantmedia.com
videoegg.com
video-stats.video.google.com
view4cash.de
viewpoint.com
visistat.com
visitbox.de
visit.webhosting.yahoo.com
visual-pagerank.fr
visualrevenue.com
voicefive.com
voicevegetable.com
vpon.com
vrs.cz
vs.tucows.com
vungle.com
warlog.ru
wdads.sx.atl.publicus.com
web2.deja.com
webads.co.nz
webads.nl
webangel.ru
webcash.nl
webcounter.cz
webcounter.goweb.de
webgains.com
web.informer.com
webmaster-partnerprogramme24.de
webmasterplan.com
webmasterplan.de
weborama.fr
webpower.com
webreseau.com
webseoanalytics.com
websponsors.com
webstat.channel4.com
web-stat.com
webstat.com
webstat.net
webstats4u.com
webtrackerplus.com
webtraffic.se
webtraxx.de
webtrendslive.com
werbung.meteoxpress.com
wetrack.it
whaleads.com
whenu.com
whispa.com
whoisonline.net
wholesaletraffic.info
widespace.com
widgetbucks.com
wikia-ads.wikia.com
window.nixnet.cz
wintricksbanner.googlepages.com
witch-counter.de
wlmarketing.com
wmirk.ru
wonderlandads.com
wondoads.de
woopra.com
worldwide-cash.net
ws-gateway.com
wtlive.com
www1.gto-media.com
www8.glam.com
www-banner.chat.ru
www.banner-link.com.br
www.dnps.com
www-google-analytics.l.google.com
www.kaplanindex.com
www.money4exit.de
www.photo-ads.co.uk
wwwpromoter.com
x6.yakiuchi.com
xchange.ro
xclicks.net
xertive.com
xg4ken.com
xiti.com
xplusone.com
xponsor.com
xq1.net
xrea.com
xtendmedia.com
x-traceur.com
xtremetop100.com
xxxcounter.com
xxxmyself.com
yab-adimages.s3.amazonaws.com
yabuka.com
yadro.ru
yesads.com
yesadvertising.com
y.ibsys.com
yieldads.com
yieldlab.net
yieldmanager.com
yieldmanager.net
yieldmo.com
yieldtraffic.com
yoc.mobi
yoggrt.com
z5x.net
zangocash.com
zanox-affiliate.de
zanox.com
zantracker.com
zedo.com
zencudo.co.uk
zenkreka.com
zenzuu.com
zeusclicks.com
zeus.developershed.com
zintext.com
zmedia.com
zv1.november-lax.com
